import { RawRundownData } from './enps-interface'

export const rawRundown3: RawRundownData = {
  TimingObj: {
    TotalCumeTime: 42,
    TotalOverUnderTime: 42,
    IsTiming: false,
    SegmentCountDown: '00:00:00',
    SegmentCountUp: '00:00:00',
    StoryCountDown: '00:00:00',
    ProgramCountDown: '00:00:00',
    FrontOverUnder: '-10675199.00:00:00',
    OverUnder: '-00:04:18',
    IsROCountDown: false,
    IsStoryCountDown: false,
    IsSegCountDown: false,
    IsROTimeEstimated: false,
  },
  CollectionScripts: [
    {
      CollectionsCollection: null,
      ScriptOrder: 1,
      PageNum: 'A1',
      FrontTime: '2023-12-29T19:00:00Z',
      FrontTimeFormatted: '07:00:00 PM',
      BackTime: '2023-12-29T19:04:18Z',
      BackTimeFormatted: '07:04:18 PM',
      FrontOverUnder: '-10675199.00:00:00',
      BackOverUnder: '-10675199.00:00:00',
      CumeTime: '00:00:00',
      CumeTimeFormatted: '0:00',
      BackCumeTime: '00:00:42',
      BackCumeTimeFormatted: '0:42',
      IsTimingBarSelected: false,
      IsRowFlashing: false,
      IsFrozen: false,
      RecordPointer: {
        ReadTime: 0,
        Actual: null,
        Estimated: '00:00:00',
        HardHitFront: '1800-01-01T00:00:00',
        HardHitBack: '1800-01-01T00:00:00',
        ActualTimeString: { Key: 'ReadTime', Value: '0:00' },
        DefaultLayout: null,
        Loading: false,
        ObjectProperties: [
          {
            FieldName: 'TextCommands',
            FieldValue: {
              'b83fd993-fc12-4bef-b240-82c797b337cd':
                '[<mos><itemID>2</itemID><itemSlug>Z INTRO 2PM UPDATE-SOT</itemSlug><objID>50b1c68e-fa17-4927-985b-c59cc215e20a</objID><mosID>zns.precis1.nassau.mos</mosID><mosAbstract>Z INTRO 2PM UPDATE-SOT_NEWSEDIT-C_Admin_20221007_125913.mxf</mosAbstract><objDur>687</objDur><objTB>60</objTB><objSlug>Z INTRO 2PM UPDATE-SOT_NEWSEDIT-C_Admin_20221007_125913.mxf</objSlug><objType>VIDEO</objType><itemChannel>A</itemChannel><itemEdStart>0</itemEdStart><itemEdDur>0</itemEdDur><objAir>NOT READY</objAir><objPaths><objPath>https://ZNS-BCCS01.znsbahamas.com:10456/broadcast/50b1c68e-fa17-4927-985b-c59cc215e20a.mxf</objPath><objProxyPath techDescription="Proxy">https://ZNS-BCCS01.znsbahamas.com:10456/proxy/50b1c68e-fa17-4927-985b-c59cc215e20aProxy.mp4</objProxyPath><objProxyPath techDescription="JPG">https://ZNS-BCCS01.znsbahamas.com:10456/still/50b1c68e-fa17-4927-985b-c59cc215e20a.jpg</objProxyPath></objPaths><mosExternalMetadata><mosScope>STORY</mosScope><mosSchema>http://bitcentral.com/schemas/mos/2.0</mosSchema><mosPayload/></mosExternalMetadata></mos>]',
            },
          },
          {
            FieldName: 'Text',
            FieldValue:
              '<html xmlns="http://www.w3.org/1999/xhtml">\r\n<head><title></title></head>\r\n<body><br /><span class="MOS-zns.precis1.nassau.mos" id="b83fd993-fc12-4bef-b240-82c797b337cd"></span><br /></body></html>',
          },
          { FieldName: 'VPContainsRTL', FieldValue: false },
          { FieldName: 'Type', FieldValue: 3 },
          { FieldName: 'Owner', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'Creator', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'AnchorTime', FieldValue: '2022-10-06T15:21:38Z' },
          { FieldName: 'Approved', FieldValue: false },
          { FieldName: 'pubApproved', FieldValue: false },
          {
            FieldName: 'GUID',
            FieldValue: 'A2021AB6-EC3D-4E5C-9B3A52C8A40D8642',
          },
          { FieldName: 'Expires', FieldValue: '2022-11-11T20:11:32Z' },
          { FieldName: 'ModTime', FieldValue: '2022-10-12T19:11:32Z' },
          { FieldName: 'Priority', FieldValue: 0 },
          { FieldName: 'Version', FieldValue: 2 },
          { FieldName: 'Status', FieldValue: '3' },
          { FieldName: 'WriteCount', FieldValue: 17 },
          { FieldName: 'RowModTime', FieldValue: '2023-12-29T18:31:15Z' },
          { FieldName: 'ScriptSubType', FieldValue: 'Broadcast' },
          { FieldName: 'LastMOSItemID', FieldValue: '2' },
          { FieldName: 'ReadTime', FieldValue: 0 },
          { FieldName: 'MediaTime', FieldValue: '00:00:00' },
          { FieldName: 'TextTime', FieldValue: '00:00:00' },
          { FieldName: 'SourceReadTime', FieldValue: 0 },
          { FieldName: 'SourceMediaTime', FieldValue: '00:00:00' },
          { FieldName: 'SourceTextTime', FieldValue: '00:00:00' },
          { FieldName: 'MOSIDs', FieldValue: 'zns.precis1.nassau.mos' },
          {
            FieldName: 'MOSObjIDs',
            FieldValue: '50b1c68e-fa17-4927-985b-c59cc215e20a',
          },
          { FieldName: 'MOSSlugs', FieldValue: 'Z INTRO 2PM UPDATE-SOT' },
          { FieldName: 'MOSItemDurations', FieldValue: '0:11' },
          {
            FieldName: 'MOSAbstracts',
            FieldValue:
              'Z INTRO 2PM UPDATE-SOT_NEWSEDIT-C_Admin_20221007_125913.mxf',
          },
          {
            FieldName: 'MOSObjSlugs',
            FieldValue:
              'Z INTRO 2PM UPDATE-SOT_NEWSEDIT-C_Admin_20221007_125913.mxf',
          },
          { FieldName: 'MOSItemIDs', FieldValue: '2' },
          { FieldName: 'MOSStatus', FieldValue: 'Linked' },
          { FieldName: 'MOSTimes', FieldValue: '7:00:59 AM' },
          { FieldName: 'MOSChannels', FieldValue: ['A'] },
          { FieldName: 'MOSItemEdDurations', FieldValue: '0:00' },
          {
            FieldName: 'MOSItemPaths',
            FieldValue:
              '<objPath>https://ZNS-BCCS01.znsbahamas.com:10456/broadcast/50b1c68e-fa17-4927-985b-c59cc215e20a.mxf</objPath><objProxyPath techDescription="Proxy">https://ZNS-BCCS01.znsbahamas.com:10456/proxy/50b1c68e-fa17-4927-985b-c59cc215e20aProxy.mp4</objProxyPath><objProxyPath techDescription="JPG">https://ZNS-BCCS01.znsbahamas.com:10456/still/50b1c68e-fa17-4927-985b-c59cc215e20a.jpg</objProxyPath>',
          },
          {
            FieldName: 'MOSItemPathsBBL',
            FieldValue:
              '<objPath>https://ZNS-BCCS01.znsbahamas.com:10456/broadcast/50b1c68e-fa17-4927-985b-c59cc215e20a.mxf</objPath><objProxyPath techDescription="Proxy">https://ZNS-BCCS01.znsbahamas.com:10456/proxy/50b1c68e-fa17-4927-985b-c59cc215e20aProxy.mp4</objProxyPath><objProxyPath techDescription="JPG">https://ZNS-BCCS01.znsbahamas.com:10456/still/50b1c68e-fa17-4927-985b-c59cc215e20a.jpg</objProxyPath>',
          },
          { FieldName: 'MOSStoryStatus', FieldValue: '' },
          { FieldName: 'MOSStoryStatusMOS', FieldValue: '' },
          {
            FieldName: 'MOSStoryStatusTime',
            FieldValue: '1800-01-01T00:00:00Z',
          },
          { FieldName: 'ModBy', FieldValue: 'O.ROACH' },
          { FieldName: 'RowModBy', FieldValue: 'L.DAVIS' },
          { FieldName: 'DoNotArchive', FieldValue: true },
          { FieldName: 'Printed', FieldValue: '2023-12-29T18:31:15Z' },
          { FieldName: 'Database', FieldValue: 'svrscala-backup' },
          {
            FieldName: 'Path',
            FieldValue: 'P_NASNEWS\\W\\R_C8E9599C-5CC9-42A0-905431F716269206',
          },
          { FieldName: 'Title', FieldValue: 'Z INTRO 2PM UPDATE-SOT' },
          { FieldName: 'OutputType', FieldValue: 0 },
          { FieldName: 'PageNum', FieldValue: 'A1' },
          { FieldName: 'UserCanWritePermissions', FieldValue: true },
          { FieldName: 'CumeTime', FieldValue: 0 },
          { FieldName: 'ObjectPlaceholderCreate', FieldValue: '' },
          { FieldName: 'Reporter', FieldValue: '' },
          { FieldName: 'Float', FieldValue: false },
          { FieldName: 'Break', FieldValue: false },
          { FieldName: 'Estimated', FieldValue: 0 },
          { FieldName: 'Actual', FieldValue: 0 },
          { FieldName: 'BackTime', FieldValue: '1800-01-01T00:00:00' },
        ],
        ListData: {
          ENPSDatabase: 'svrscala-backup',
          Path: 'P_NASNEWS\\W\\R_C8E9599C-5CC9-42A0-905431F716269206',
          Guid: 'A2021AB6-EC3D-4E5C-9B3A52C8A40D8642',
          ContainerTitle: '2PM Update',
          Title: 'Z INTRO 2PM UPDATE-SOT',
          Type: 3,
          Priority: 0,
          Approved: false,
          OutputType: 0,
          Creator: 'J.SAUNDERS',
          ModBy: 'O.ROACH',
          MosObjId: '',
          MosControl: false,
          ModTime: '2022-10-12T19:11:32Z',
          Expires: '2022-11-11T20:11:32Z',
          Owner: 'J.SAUNDERS',
          BeginText: '\r\n\r\n',
          FileStorageVersion: 0,
        },
        ObjectLinks: { LinkedRecords: { $id: '1', $values: [] } },
        SocialMediaLinks: [],
        ObjectTags: { Tags: [] },
        ChatData: [],
        IsSearchReturnedResult: false,
      },
      Float: false,
      Break: false,
      HasYellowTimingBar: false,
      CBreak: false,
      NotForBroadcast: false,
    },
    {
      CollectionsCollection: null,
      ScriptOrder: 2,
      PageNum: 'A2',
      FrontTime: '2023-12-29T19:00:00Z',
      FrontTimeFormatted: '07:00:00 PM',
      BackTime: '2023-12-29T19:04:18Z',
      BackTimeFormatted: '07:04:18 PM',
      FrontOverUnder: '-10675199.00:00:00',
      BackOverUnder: '-10675199.00:00:00',
      CumeTime: '00:00:13',
      CumeTimeFormatted: '0:13',
      BackCumeTime: '00:00:42',
      BackCumeTimeFormatted: '0:42',
      IsTimingBarSelected: false,
      IsRowFlashing: false,
      IsFrozen: false,
      RecordPointer: {
        ReadTime: 13,
        Actual: null,
        Estimated: '00:00:00',
        HardHitFront: '1800-01-01T00:00:00',
        HardHitBack: '1800-01-01T00:00:00',
        ActualTimeString: { Key: 'ReadTime', Value: '0:13' },
        DefaultLayout: null,
        Loading: false,
        ObjectProperties: [
          { FieldName: 'TextCommands', FieldValue: {} },
          {
            FieldName: 'Text',
            FieldValue:
              '<html xmlns="http://www.w3.org/1999/xhtml">\r\n<head><title></title></head>\r\n<body><span>THIS&#160;IS&#160;ZNS&#160;NEWS&#160;HEADLINES&#160;AT&#160;THE&#160;HOUR...&#160;GOOD&#160;AFTERNOON&#160;EVERYONE,&#160;IM&#160;LEDAUNNE&#160;DAVIS...&#160;HERE\'S&#160;SOME&#160;OF&#160;THE&#160;STORIES&#160;WE\'RE&#160;WORKING&#160;ON.<br /><br />\r\nTHE&#160;COUNTDOWN&#160;IS&#160;NOW&#160;ON&#160;FOR&#160;THE&#160;NEW&#160;YEARS&#160;DAY&#160;JUNKNAOO&#160;PARADE&#160;AND&#160;JCNP&#160;OFFICIALS&#160;ARE&#160;NOW&#160;&#160;HARD&#160;AT&#160;WORK&#160;RECTIFYING&#160;SOME&#160;OF&#160;THE&#160;KINKS&#160;EXPERIENCED&#160;AT&#160;THE&#160;BOXING&#160;DAY&#160;PARADE...<br />\r\n=====</span></body></html>',
          },
          { FieldName: 'VPContainsRTL', FieldValue: false },
          { FieldName: 'Owner', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'Creator', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'ModBy', FieldValue: 'L.DAVIS' },
          { FieldName: 'AnchorTime', FieldValue: '2019-07-19T16:08:23Z' },
          { FieldName: 'Expires', FieldValue: '2024-01-28T18:20:27Z' },
          { FieldName: 'ModTime', FieldValue: '2023-12-29T18:20:27Z' },
          { FieldName: 'Type', FieldValue: 3 },
          { FieldName: 'SourceModBy', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'SourceModTime', FieldValue: '2019-07-19T16:07:06Z' },
          {
            FieldName: 'GUID',
            FieldValue: '967C6254-BBE5-4182-8ED6E22E92CEBDD9',
          },
          { FieldName: 'pubApproved', FieldValue: false },
          { FieldName: 'ScriptSubType', FieldValue: 'Broadcast' },
          { FieldName: 'Priority', FieldValue: 0 },
          { FieldName: 'Approved', FieldValue: false },
          { FieldName: 'Version', FieldValue: 1 },
          { FieldName: 'Status', FieldValue: '3' },
          { FieldName: 'WriteCount', FieldValue: 7 },
          { FieldName: 'RowModTime', FieldValue: '2023-12-29T18:31:15Z' },
          { FieldName: 'RowModBy', FieldValue: 'L.DAVIS' },
          { FieldName: 'ReadTime', FieldValue: 13 },
          { FieldName: 'MediaTime', FieldValue: '00:00:00' },
          { FieldName: 'TextTime', FieldValue: '00:00:13' },
          { FieldName: 'SourceReadTime', FieldValue: 0 },
          { FieldName: 'SourceMediaTime', FieldValue: '00:00:00' },
          { FieldName: 'SourceTextTime', FieldValue: '00:00:00' },
          {
            FieldName: 'OutCue',
            FieldValue: 'EXPERIENCED AT THE BOXING DAY PARADE... =====',
          },
          { FieldName: 'LastKbdUsed', FieldValue: '67699721' },
          { FieldName: 'Printed', FieldValue: '2023-12-29T18:31:15Z' },
          { FieldName: 'Database', FieldValue: 'svrscala-backup' },
          {
            FieldName: 'Path',
            FieldValue: 'P_NASNEWS\\W\\R_C8E9599C-5CC9-42A0-905431F716269206',
          },
          { FieldName: 'Title', FieldValue: 'JCNP ON JUNKANOO- SCRIPT' },
          { FieldName: 'OutputType', FieldValue: 0 },
          { FieldName: 'PageNum', FieldValue: 'A2' },
          { FieldName: 'UserCanWritePermissions', FieldValue: true },
          { FieldName: 'CumeTime', FieldValue: 0 },
          { FieldName: 'DoNotArchive', FieldValue: false },
          { FieldName: 'MOSObjSlugs', FieldValue: '' },
          { FieldName: 'ObjectPlaceholderCreate', FieldValue: '' },
          { FieldName: 'MOSChannels', FieldValue: '' },
          { FieldName: 'Reporter', FieldValue: '' },
          { FieldName: 'MOSStatus', FieldValue: '' },
          { FieldName: 'Float', FieldValue: false },
          { FieldName: 'Break', FieldValue: false },
          { FieldName: 'Estimated', FieldValue: 0 },
          { FieldName: 'Actual', FieldValue: 0 },
          { FieldName: 'BackTime', FieldValue: '1800-01-01T00:00:00' },
        ],
        ListData: {
          ENPSDatabase: 'svrscala-backup',
          Path: 'P_NASNEWS\\W\\R_C8E9599C-5CC9-42A0-905431F716269206',
          Guid: '967C6254-BBE5-4182-8ED6E22E92CEBDD9',
          ContainerTitle: '2PM Update',
          Title: 'JCNP ON JUNKANOO- SCRIPT',
          Type: 3,
          Priority: 0,
          Approved: false,
          OutputType: 0,
          Creator: 'J.SAUNDERS',
          ModBy: 'L.DAVIS',
          MosObjId: '',
          MosControl: false,
          ModTime: '2023-12-29T18:20:27Z',
          Expires: '2024-01-28T18:20:27Z',
          Owner: 'J.SAUNDERS',
          BeginText:
            "THIS IS ZNS NEWS HEADLINES AT THE HOUR... GOOD AFTERNOON EVERYONE, IM LEDAUNNE DAVIS... HERE'S SOME OF THE STORIES WE'RE WORKING ON.\r\n\r\nTHE COUNTDOWN IS NOW ON FOR THE NEW YEARS DAY JUNKNAOO PARADE AND JCNP OFFICIALS ARE NOW  HARD AT WORK RECTIFYING SOME OF THE KINKS EXPERIENCED AT THE BOXING DAY PARADE...\r\n=====",
          FileStorageVersion: 0,
        },
        ObjectLinks: { LinkedRecords: { $id: '2', $values: [] } },
        SocialMediaLinks: [],
        ObjectTags: { Tags: [] },
        ChatData: [],
        IsSearchReturnedResult: false,
      },
      Float: false,
      Break: false,
      HasYellowTimingBar: false,
      CBreak: false,
      NotForBroadcast: false,
    },
    {
      CollectionsCollection: null,
      ScriptOrder: 3,
      PageNum: 'A3',
      FrontTime: '2023-12-29T19:00:13Z',
      FrontTimeFormatted: '07:00:13 PM',
      BackTime: '2023-12-29T19:04:31Z',
      BackTimeFormatted: '07:04:31 PM',
      FrontOverUnder: '-10675199.00:00:00',
      BackOverUnder: '-10675199.00:00:00',
      CumeTime: '00:00:26',
      CumeTimeFormatted: '0:26',
      BackCumeTime: '00:00:29',
      BackCumeTimeFormatted: '0:29',
      IsTimingBarSelected: false,
      IsRowFlashing: false,
      IsFrozen: false,
      RecordPointer: {
        ReadTime: 13,
        Actual: null,
        Estimated: '00:00:00',
        HardHitFront: '1800-01-01T00:00:00',
        HardHitBack: '1800-01-01T00:00:00',
        ActualTimeString: { Key: 'ReadTime', Value: '0:13' },
        DefaultLayout: null,
        Loading: false,
        ObjectProperties: [
          { FieldName: 'TextCommands', FieldValue: {} },
          {
            FieldName: 'Text',
            FieldValue:
              '<html xmlns="http://www.w3.org/1999/xhtml">\r\n<head><title></title></head>\r\n<body><span xml:lang="en-us" style="background-color:#FFFFFF;color:#000000;">EXPECT&#160;TO&#160;SEE&#160;A&#160;STRONGER&#160;PRESENCE&#160;BY&#160;THE&#160;BAHAMAS&#160;CHRISTIAN&#160;COUNCIL&#160;IN&#160;THE&#160;NEW&#160;YEAR...THE&#160;COUNCIL&#160;PRESIDENT&#160;TELLING&#160;ZNS&#160;NEWS&#160;THAT&#160;HE\'S&#160;CONCERNED&#160;ABOUT&#160;A&#160;NUMBER&#160;OF&#160;SOCIAL&#160;ILLS&#160;PLAGUING&#160;THE&#160;COUNTRY,&#160;ESPECIALLY&#160;THE&#160;ESCALATING&#160;MURDER&#160;COUNT&#160;THATS&#160;HIT&#160;A&#160;RECORD&#160;108&#160;FOR&#160;THE&#160;YEAR...</span><br /><span xml:lang="en-us" style="background-color:#FFFFFF;color:#000000;">=========================</span><span><br /><br /><br /></span></body></html>',
          },
          { FieldName: 'VPContainsRTL', FieldValue: false },
          { FieldName: 'Owner', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'Creator', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'ModBy', FieldValue: 'J.BENSON' },
          { FieldName: 'AnchorTime', FieldValue: '2019-07-19T16:08:23Z' },
          { FieldName: 'Expires', FieldValue: '2024-01-28T18:30:39Z' },
          { FieldName: 'ModTime', FieldValue: '2023-12-29T18:30:39Z' },
          { FieldName: 'Type', FieldValue: 3 },
          { FieldName: 'SourceModBy', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'SourceModTime', FieldValue: '2019-07-19T16:07:14Z' },
          {
            FieldName: 'GUID',
            FieldValue: '883D6ED5-10B2-4096-9479316D9CC97F22',
          },
          { FieldName: 'pubApproved', FieldValue: false },
          { FieldName: 'ScriptSubType', FieldValue: 'Broadcast' },
          { FieldName: 'Priority', FieldValue: 0 },
          { FieldName: 'Approved', FieldValue: false },
          { FieldName: 'Version', FieldValue: 2 },
          { FieldName: 'Status', FieldValue: '3' },
          { FieldName: 'WriteCount', FieldValue: 8 },
          { FieldName: 'RowModTime', FieldValue: '2023-12-29T18:31:15Z' },
          { FieldName: 'RowModBy', FieldValue: 'L.DAVIS' },
          { FieldName: 'ReadTime', FieldValue: 13 },
          { FieldName: 'MediaTime', FieldValue: '00:00:00' },
          { FieldName: 'TextTime', FieldValue: '00:00:13' },
          { FieldName: 'SourceReadTime', FieldValue: 0 },
          { FieldName: 'SourceMediaTime', FieldValue: '00:00:00' },
          { FieldName: 'SourceTextTime', FieldValue: '00:00:13' },
          {
            FieldName: 'OutCue',
            FieldValue: '108 FOR THE YEAR... =========================',
          },
          { FieldName: 'Fontname', FieldValue: 'Arial' },
          { FieldName: 'LastKbdUsed', FieldValue: '67699721' },
          {
            FieldName: 'LastEditorInfo',
            FieldValue: 'Edited on .net Client at 29/12/2023 6:30:10 pm',
          },
          { FieldName: 'ScriptWordCount', FieldValue: '46' },
          { FieldName: 'SelReadTime', FieldValue: '0' },
          { FieldName: 'SelSourceReadTime', FieldValue: '0' },
          { FieldName: 'Locked', FieldValue: false },
          { FieldName: 'SelMediaTime', FieldValue: '0' },
          { FieldName: 'SelTextTime', FieldValue: '0' },
          { FieldName: 'SelSourceMediaTime', FieldValue: '0' },
          { FieldName: 'SelSourceTextTime', FieldValue: '0' },
          { FieldName: 'Printed', FieldValue: '2023-12-29T18:31:16Z' },
          { FieldName: 'Database', FieldValue: 'svrscala-backup' },
          {
            FieldName: 'Path',
            FieldValue: 'P_NASNEWS\\W\\R_C8E9599C-5CC9-42A0-905431F716269206',
          },
          {
            FieldName: 'Title',
            FieldValue: 'CHRISTIAN COUNCIL ON COUNTRY AND CRIME- SCRIPT',
          },
          { FieldName: 'OutputType', FieldValue: 0 },
          { FieldName: 'PageNum', FieldValue: 'A3' },
          { FieldName: 'UserCanWritePermissions', FieldValue: true },
          { FieldName: 'CumeTime', FieldValue: 0 },
          { FieldName: 'DoNotArchive', FieldValue: false },
          { FieldName: 'MOSObjSlugs', FieldValue: '' },
          { FieldName: 'ObjectPlaceholderCreate', FieldValue: '' },
          { FieldName: 'MOSChannels', FieldValue: '' },
          { FieldName: 'Reporter', FieldValue: '' },
          { FieldName: 'MOSStatus', FieldValue: '' },
          { FieldName: 'Float', FieldValue: false },
          { FieldName: 'Break', FieldValue: false },
          { FieldName: 'Estimated', FieldValue: 0 },
          { FieldName: 'Actual', FieldValue: 0 },
          { FieldName: 'BackTime', FieldValue: '1800-01-01T00:00:00' },
        ],
        ListData: {
          ENPSDatabase: 'svrscala-backup',
          Path: 'P_NASNEWS\\W\\R_C8E9599C-5CC9-42A0-905431F716269206',
          Guid: '883D6ED5-10B2-4096-9479316D9CC97F22',
          ContainerTitle: '2PM Update',
          Title: 'CHRISTIAN COUNCIL ON COUNTRY AND CRIME- SCRIPT',
          Type: 3,
          Priority: 0,
          Approved: false,
          OutputType: 0,
          Creator: 'J.SAUNDERS',
          ModBy: 'J.BENSON',
          MosObjId: '',
          MosControl: false,
          ModTime: '2023-12-29T18:30:39Z',
          Expires: '2024-01-28T18:30:39Z',
          Owner: 'J.SAUNDERS',
          BeginText:
            "EXPECT TO SEE A STRONGER PRESENCE BY THE BAHAMAS CHRISTIAN COUNCIL IN THE NEW YEAR...THE COUNCIL PRESIDENT TELLING ZNS NEWS THAT HE'S CONCERNED ABOUT A NUMBER OF SOCIAL ILLS PLAGUING THE COUNTRY, ESPECIALLY THE ESCALATING MURDER COUNT THATS HIT A RECORD 108 FOR THE YEAR...\r\n=========================\r\n\r\n\r\n",
          FileStorageVersion: 0,
        },
        ObjectLinks: { LinkedRecords: { $id: '3', $values: [] } },
        SocialMediaLinks: [],
        ObjectTags: { Tags: [] },
        ChatData: [],
        IsSearchReturnedResult: false,
      },
      Float: false,
      Break: false,
      HasYellowTimingBar: false,
      CBreak: false,
      NotForBroadcast: false,
    },
    {
      CollectionsCollection: null,
      ScriptOrder: 4,
      PageNum: 'A4',
      FrontTime: '2023-12-29T19:00:26Z',
      FrontTimeFormatted: '07:00:26 PM',
      BackTime: '2023-12-29T19:04:44Z',
      BackTimeFormatted: '07:04:44 PM',
      FrontOverUnder: '-10675199.00:00:00',
      BackOverUnder: '-10675199.00:00:00',
      CumeTime: '00:00:42',
      CumeTimeFormatted: '0:42',
      BackCumeTime: '00:00:16',
      BackCumeTimeFormatted: '0:16',
      IsTimingBarSelected: false,
      IsRowFlashing: false,
      IsFrozen: false,
      RecordPointer: {
        ReadTime: 16,
        Actual: null,
        Estimated: '00:00:00',
        HardHitFront: '1800-01-01T00:00:00',
        HardHitBack: '1800-01-01T00:00:00',
        ActualTimeString: { Key: 'ReadTime', Value: '0:16' },
        DefaultLayout: null,
        Loading: false,
        ObjectProperties: [
          { FieldName: 'TextCommands', FieldValue: {} },
          {
            FieldName: 'Text',
            FieldValue:
              '<html xmlns="http://www.w3.org/1999/xhtml">\r\n<head><title></title></head>\r\n<body><span>AND&#160;A&#160;&#160;THIRTY&#160;SIX&#160;YEAR&#160;OLD&#160;MAN&#160;IS&#160;IN&#160;POLICE&#160;CUSTODY&#160;AFTER&#160;HE&#160;FATALLY&#160;STABBED&#160;ANOTHER&#160;MAN&#160;DURING&#160;A&#160;DISPUTE&#160;ON&#160;FINLAYSON&#160;STSREET.&#160;HE&#160;&#160;FLED&#160;THE&#160;SCENE&#160;OF&#160;THE&#160;CRIME&#160;&#160;BUT&#160;EVENTUALLY&#160;TURNED&#160;HIMSELF&#160;IN&#160;HOURS&#160;LATER..THE&#160;VICTIM&#160;IS&#160;STILL&#160;NURSING&#160;WOUNDS&#160;IN&#160;HOSPITAL...&#160;<br />\r\n==============<br /><br />\r\nAND&#160;THAT\'S&#160;&#160;STORIES&#160;MAKING&#160;NEWS&#160;AT&#160;THIS&#160;HOUR...&#160;ONCE&#160;AGAIN,&#160;IM&#160;LEDAUNNE&#160;DAVIS...&#160;GOOD&#160;AFTERNOON.&#160;<br /></span></body></html>',
          },
          { FieldName: 'VPContainsRTL', FieldValue: false },
          { FieldName: 'Owner', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'Creator', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'ModBy', FieldValue: 'L.DAVIS' },
          { FieldName: 'AnchorTime', FieldValue: '2019-07-19T16:08:23Z' },
          { FieldName: 'Expires', FieldValue: '2024-01-28T18:28:11Z' },
          { FieldName: 'ModTime', FieldValue: '2023-12-29T18:28:11Z' },
          { FieldName: 'Type', FieldValue: 3 },
          { FieldName: 'SourceModBy', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'SourceModTime', FieldValue: '2019-07-19T16:07:10Z' },
          {
            FieldName: 'GUID',
            FieldValue: '5B505340-8D9B-46BB-AF596118684DE08D',
          },
          { FieldName: 'pubApproved', FieldValue: false },
          { FieldName: 'ScriptSubType', FieldValue: 'Broadcast' },
          { FieldName: 'Priority', FieldValue: 0 },
          { FieldName: 'Approved', FieldValue: false },
          { FieldName: 'Version', FieldValue: 2 },
          { FieldName: 'Status', FieldValue: '3' },
          { FieldName: 'WriteCount', FieldValue: 10 },
          { FieldName: 'RowModTime', FieldValue: '2023-12-29T18:31:16Z' },
          { FieldName: 'RowModBy', FieldValue: 'L.DAVIS' },
          { FieldName: 'ReadTime', FieldValue: 16 },
          { FieldName: 'MediaTime', FieldValue: '00:00:00' },
          { FieldName: 'TextTime', FieldValue: '00:00:16' },
          { FieldName: 'SourceReadTime', FieldValue: 0 },
          { FieldName: 'SourceMediaTime', FieldValue: '00:00:00' },
          { FieldName: 'SourceTextTime', FieldValue: '00:00:00' },
          {
            FieldName: 'OutCue',
            FieldValue: 'ONCE AGAIN, IM LEDAUNNE DAVIS... GOOD AFTERNOON. ',
          },
          { FieldName: 'LastKbdUsed', FieldValue: '67699721' },
          { FieldName: 'Printed', FieldValue: '2023-12-29T18:31:16Z' },
          { FieldName: 'Database', FieldValue: 'svrscala-backup' },
          {
            FieldName: 'Path',
            FieldValue: 'P_NASNEWS\\W\\R_C8E9599C-5CC9-42A0-905431F716269206',
          },
          { FieldName: 'Title', FieldValue: 'FATAL STABBING-SCRIPT' },
          { FieldName: 'OutputType', FieldValue: 0 },
          { FieldName: 'PageNum', FieldValue: 'A4' },
          { FieldName: 'UserCanWritePermissions', FieldValue: true },
          { FieldName: 'CumeTime', FieldValue: 0 },
          { FieldName: 'DoNotArchive', FieldValue: false },
          { FieldName: 'MOSObjSlugs', FieldValue: '' },
          { FieldName: 'ObjectPlaceholderCreate', FieldValue: '' },
          { FieldName: 'MOSChannels', FieldValue: '' },
          { FieldName: 'Reporter', FieldValue: '' },
          { FieldName: 'MOSStatus', FieldValue: '' },
          { FieldName: 'Float', FieldValue: false },
          { FieldName: 'Break', FieldValue: false },
          { FieldName: 'Estimated', FieldValue: 0 },
          { FieldName: 'Actual', FieldValue: 0 },
          { FieldName: 'BackTime', FieldValue: '1800-01-01T00:00:00' },
        ],
        ListData: {
          ENPSDatabase: 'svrscala-backup',
          Path: 'P_NASNEWS\\W\\R_C8E9599C-5CC9-42A0-905431F716269206',
          Guid: '5B505340-8D9B-46BB-AF596118684DE08D',
          ContainerTitle: '2PM Update',
          Title: 'FATAL STABBING-SCRIPT',
          Type: 3,
          Priority: 0,
          Approved: false,
          OutputType: 0,
          Creator: 'J.SAUNDERS',
          ModBy: 'L.DAVIS',
          MosObjId: '',
          MosControl: false,
          ModTime: '2023-12-29T18:28:11Z',
          Expires: '2024-01-28T18:28:11Z',
          Owner: 'J.SAUNDERS',
          BeginText:
            "AND A  THIRTY SIX YEAR OLD MAN IS IN POLICE CUSTODY AFTER HE FATALLY STABBED ANOTHER MAN DURING A DISPUTE ON FINLAYSON STSREET. HE  FLED THE SCENE OF THE CRIME  BUT EVENTUALLY TURNED HIMSELF IN HOURS LATER..THE VICTIM IS STILL NURSING WOUNDS IN HOSPITAL... \r\n==============\r\n\r\nAND THAT'S  STORIES MAKING NEWS AT THIS HOUR... ONCE AGAIN, IM LEDAUNNE DAVIS... GOOD AFTERNOON. \r\n",
          FileStorageVersion: 0,
        },
        ObjectLinks: { LinkedRecords: { $id: '4', $values: [] } },
        SocialMediaLinks: [],
        ObjectTags: { Tags: [] },
        ChatData: [],
        IsSearchReturnedResult: false,
      },
      Float: false,
      Break: false,
      HasYellowTimingBar: false,
      CBreak: false,
      NotForBroadcast: false,
    },
    {
      CollectionsCollection: null,
      ScriptOrder: 5,
      PageNum: 'A5',
      FrontTime: '2023-12-29T19:00:42Z',
      FrontTimeFormatted: '07:00:42 PM',
      BackTime: '2023-12-29T19:05:00Z',
      BackTimeFormatted: '07:05:00 PM',
      FrontOverUnder: '-10675199.00:00:00',
      BackOverUnder: '-10675199.00:00:00',
      CumeTime: '00:00:42',
      CumeTimeFormatted: '0:42',
      BackCumeTime: '00:00:00',
      BackCumeTimeFormatted: '0:00',
      IsTimingBarSelected: false,
      IsRowFlashing: false,
      IsFrozen: false,
      RecordPointer: {
        ReadTime: 0,
        Actual: null,
        Estimated: '00:00:00',
        HardHitFront: '1800-01-01T00:00:00',
        HardHitBack: '1800-01-01T00:00:00',
        ActualTimeString: { Key: 'ReadTime', Value: '0:00' },
        DefaultLayout: null,
        Loading: false,
        ObjectProperties: [
          {
            FieldName: 'TextCommands',
            FieldValue: {
              'b7040f45-134d-41f3-81ad-6779942732cc':
                '[<mos><itemID>2</itemID><itemSlug>Z EXTRO 2PM UPDATE-SOT</itemSlug><objID>54dd9610-0cf0-49eb-8c86-a50d2bafb067</objID><mosID>zns.precis1.nassau.mos</mosID><mosAbstract>Z EXTRO 2PM UPDATE-SOT_NEWSEDIT-C_Admin_20221007_125935.mxf</mosAbstract><objDur>687</objDur><objTB>60</objTB><objSlug>Z EXTRO 2PM UPDATE-SOT_NEWSEDIT-C_Admin_20221007_125935.mxf</objSlug><objType>VIDEO</objType><itemChannel>A</itemChannel><itemEdStart>0</itemEdStart><itemEdDur>0</itemEdDur><objAir>NOT READY</objAir><objPaths><objPath>https://ZNS-BCCS01.znsbahamas.com:10456/broadcast/54dd9610-0cf0-49eb-8c86-a50d2bafb067.mxf</objPath><objProxyPath techDescription="Proxy">https://ZNS-BCCS01.znsbahamas.com:10456/proxy/54dd9610-0cf0-49eb-8c86-a50d2bafb067Proxy.mp4</objProxyPath><objProxyPath techDescription="JPG">https://ZNS-BCCS01.znsbahamas.com:10456/still/54dd9610-0cf0-49eb-8c86-a50d2bafb067.jpg</objProxyPath></objPaths><mosExternalMetadata><mosScope>STORY</mosScope><mosSchema>http://bitcentral.com/schemas/mos/2.0</mosSchema><mosPayload/></mosExternalMetadata></mos>]',
            },
          },
          {
            FieldName: 'Text',
            FieldValue:
              '<html xmlns="http://www.w3.org/1999/xhtml">\r\n<head><title></title></head>\r\n<body><br /><span class="MOS-zns.precis1.nassau.mos" id="b7040f45-134d-41f3-81ad-6779942732cc"></span><br /></body></html>',
          },
          { FieldName: 'VPContainsRTL', FieldValue: false },
          { FieldName: 'Type', FieldValue: 3 },
          { FieldName: 'Owner', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'Creator', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'AnchorTime', FieldValue: '2022-10-06T15:21:38Z' },
          { FieldName: 'Approved', FieldValue: false },
          { FieldName: 'pubApproved', FieldValue: false },
          {
            FieldName: 'GUID',
            FieldValue: 'B34B5A74-77D8-42A7-94B8549898650F4F',
          },
          { FieldName: 'Expires', FieldValue: '2022-11-11T20:11:36Z' },
          { FieldName: 'ModTime', FieldValue: '2022-10-12T19:11:36Z' },
          { FieldName: 'Priority', FieldValue: 0 },
          { FieldName: 'Version', FieldValue: 2 },
          { FieldName: 'Status', FieldValue: '3' },
          { FieldName: 'WriteCount', FieldValue: 19 },
          { FieldName: 'RowModTime', FieldValue: '2023-12-29T18:31:16Z' },
          { FieldName: 'ScriptSubType', FieldValue: 'Broadcast' },
          { FieldName: 'LastMOSItemID', FieldValue: '2' },
          { FieldName: 'ReadTime', FieldValue: 0 },
          { FieldName: 'MediaTime', FieldValue: '00:00:00' },
          { FieldName: 'TextTime', FieldValue: '00:00:00' },
          { FieldName: 'SourceReadTime', FieldValue: 0 },
          { FieldName: 'SourceMediaTime', FieldValue: '00:00:00' },
          { FieldName: 'SourceTextTime', FieldValue: '00:00:00' },
          { FieldName: 'MOSIDs', FieldValue: 'zns.precis1.nassau.mos' },
          {
            FieldName: 'MOSObjIDs',
            FieldValue: '54dd9610-0cf0-49eb-8c86-a50d2bafb067',
          },
          { FieldName: 'MOSSlugs', FieldValue: 'Z EXTRO 2PM UPDATE-SOT' },
          { FieldName: 'MOSItemDurations', FieldValue: '0:11' },
          {
            FieldName: 'MOSAbstracts',
            FieldValue:
              'Z EXTRO 2PM UPDATE-SOT_NEWSEDIT-C_Admin_20221007_125935.mxf',
          },
          {
            FieldName: 'MOSObjSlugs',
            FieldValue:
              'Z EXTRO 2PM UPDATE-SOT_NEWSEDIT-C_Admin_20221007_125935.mxf',
          },
          { FieldName: 'MOSItemIDs', FieldValue: '2' },
          { FieldName: 'MOSStatus', FieldValue: 'Linked' },
          { FieldName: 'MOSTimes', FieldValue: '7:01:00 AM' },
          { FieldName: 'MOSChannels', FieldValue: ['A'] },
          { FieldName: 'MOSItemEdDurations', FieldValue: '0:00' },
          {
            FieldName: 'MOSItemPaths',
            FieldValue:
              '<objPath>https://ZNS-BCCS01.znsbahamas.com:10456/broadcast/54dd9610-0cf0-49eb-8c86-a50d2bafb067.mxf</objPath><objProxyPath techDescription="Proxy">https://ZNS-BCCS01.znsbahamas.com:10456/proxy/54dd9610-0cf0-49eb-8c86-a50d2bafb067Proxy.mp4</objProxyPath><objProxyPath techDescription="JPG">https://ZNS-BCCS01.znsbahamas.com:10456/still/54dd9610-0cf0-49eb-8c86-a50d2bafb067.jpg</objProxyPath>',
          },
          {
            FieldName: 'MOSItemPathsBBL',
            FieldValue:
              '<objPath>https://ZNS-BCCS01.znsbahamas.com:10456/broadcast/54dd9610-0cf0-49eb-8c86-a50d2bafb067.mxf</objPath><objProxyPath techDescription="Proxy">https://ZNS-BCCS01.znsbahamas.com:10456/proxy/54dd9610-0cf0-49eb-8c86-a50d2bafb067Proxy.mp4</objProxyPath><objProxyPath techDescription="JPG">https://ZNS-BCCS01.znsbahamas.com:10456/still/54dd9610-0cf0-49eb-8c86-a50d2bafb067.jpg</objProxyPath>',
          },
          { FieldName: 'MOSStoryStatus', FieldValue: '' },
          { FieldName: 'MOSStoryStatusMOS', FieldValue: '' },
          {
            FieldName: 'MOSStoryStatusTime',
            FieldValue: '1800-01-01T00:00:00Z',
          },
          { FieldName: 'ModBy', FieldValue: 'O.ROACH' },
          { FieldName: 'RowModBy', FieldValue: 'L.DAVIS' },
          { FieldName: 'DoNotArchive', FieldValue: true },
          { FieldName: 'Printed', FieldValue: '2023-12-29T18:31:16Z' },
          { FieldName: 'Database', FieldValue: 'svrscala-backup' },
          {
            FieldName: 'Path',
            FieldValue: 'P_NASNEWS\\W\\R_C8E9599C-5CC9-42A0-905431F716269206',
          },
          { FieldName: 'Title', FieldValue: 'Z EXTRO 2PM UPDATE-SOT' },
          { FieldName: 'OutputType', FieldValue: 0 },
          { FieldName: 'PageNum', FieldValue: 'A5' },
          { FieldName: 'UserCanWritePermissions', FieldValue: true },
          { FieldName: 'CumeTime', FieldValue: 0 },
          { FieldName: 'ObjectPlaceholderCreate', FieldValue: '' },
          { FieldName: 'Reporter', FieldValue: '' },
          { FieldName: 'Float', FieldValue: false },
          { FieldName: 'Break', FieldValue: false },
          { FieldName: 'Estimated', FieldValue: 0 },
          { FieldName: 'Actual', FieldValue: 0 },
          { FieldName: 'BackTime', FieldValue: '1800-01-01T00:00:00' },
        ],
        ListData: {
          ENPSDatabase: 'svrscala-backup',
          Path: 'P_NASNEWS\\W\\R_C8E9599C-5CC9-42A0-905431F716269206',
          Guid: 'B34B5A74-77D8-42A7-94B8549898650F4F',
          ContainerTitle: '2PM Update',
          Title: 'Z EXTRO 2PM UPDATE-SOT',
          Type: 3,
          Priority: 0,
          Approved: false,
          OutputType: 0,
          Creator: 'J.SAUNDERS',
          ModBy: 'O.ROACH',
          MosObjId: '',
          MosControl: false,
          ModTime: '2022-10-12T19:11:36Z',
          Expires: '2022-11-11T20:11:36Z',
          Owner: 'J.SAUNDERS',
          BeginText: '\r\n\r\n',
          FileStorageVersion: 0,
        },
        ObjectLinks: { LinkedRecords: { $id: '5', $values: [] } },
        SocialMediaLinks: [],
        ObjectTags: { Tags: [] },
        ChatData: [],
        IsSearchReturnedResult: false,
      },
      Float: false,
      Break: false,
      HasYellowTimingBar: false,
      CBreak: false,
      NotForBroadcast: false,
    },
    {
      CollectionsCollection: null,
      ScriptOrder: 6,
      PageNum: 'A6',
      FrontTime: '2023-12-29T19:00:42Z',
      FrontTimeFormatted: '07:00:42 PM',
      BackTime: '2023-12-29T19:05:00Z',
      BackTimeFormatted: '07:05:00 PM',
      FrontOverUnder: '-10675199.00:00:00',
      BackOverUnder: '-10675199.00:00:00',
      CumeTime: '00:00:42',
      CumeTimeFormatted: '0:42',
      BackCumeTime: '00:00:00',
      BackCumeTimeFormatted: '0:00',
      IsTimingBarSelected: false,
      IsRowFlashing: false,
      IsFrozen: false,
      RecordPointer: {
        ReadTime: 0,
        Actual: null,
        Estimated: '00:00:00',
        HardHitFront: '1800-01-01T00:00:00',
        HardHitBack: '1800-01-01T00:00:00',
        ActualTimeString: { Key: 'ReadTime', Value: '0:00' },
        DefaultLayout: null,
        Loading: false,
        ObjectProperties: [
          { FieldName: 'TextCommands', FieldValue: {} },
          { FieldName: 'Text', FieldValue: '' },
          { FieldName: 'VPContainsRTL', FieldValue: false },
          { FieldName: 'Owner', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'Creator', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'ModBy', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'AnchorTime', FieldValue: '2019-07-19T16:08:23Z' },
          { FieldName: 'Expires', FieldValue: '2019-08-18T16:08:23Z' },
          { FieldName: 'ModTime', FieldValue: '2019-07-19T16:08:23Z' },
          { FieldName: 'Type', FieldValue: 3 },
          { FieldName: 'SourceModBy', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'SourceModTime', FieldValue: '2019-07-19T16:07:16Z' },
          {
            FieldName: 'GUID',
            FieldValue: 'F2EA857A-6D3C-42EA-BD005DC44062A776',
          },
          { FieldName: 'pubApproved', FieldValue: false },
          { FieldName: 'ScriptSubType', FieldValue: 'Broadcast' },
          { FieldName: 'Priority', FieldValue: 0 },
          { FieldName: 'Approved', FieldValue: false },
          { FieldName: 'Version', FieldValue: 0 },
          { FieldName: 'Status', FieldValue: '2' },
          { FieldName: 'WriteCount', FieldValue: 4 },
          { FieldName: 'RowModTime', FieldValue: '2023-12-29T12:00:55Z' },
          { FieldName: 'RowModBy', FieldValue: 'AutoCreate' },
          { FieldName: 'Database', FieldValue: 'svrscala-backup' },
          {
            FieldName: 'Path',
            FieldValue: 'P_NASNEWS\\W\\R_C8E9599C-5CC9-42A0-905431F716269206',
          },
          { FieldName: 'Title', FieldValue: 'New Row 4 Jason Saunders' },
          { FieldName: 'OutputType', FieldValue: 0 },
          { FieldName: 'PageNum', FieldValue: 'A6' },
          { FieldName: 'UserCanWritePermissions', FieldValue: true },
          { FieldName: 'CumeTime', FieldValue: 0 },
          { FieldName: 'DoNotArchive', FieldValue: false },
          { FieldName: 'MOSObjSlugs', FieldValue: '' },
          { FieldName: 'ObjectPlaceholderCreate', FieldValue: '' },
          { FieldName: 'MOSChannels', FieldValue: '' },
          { FieldName: 'Reporter', FieldValue: '' },
          { FieldName: 'MOSStatus', FieldValue: '' },
          { FieldName: 'Float', FieldValue: false },
          { FieldName: 'Break', FieldValue: false },
          { FieldName: 'Estimated', FieldValue: 0 },
          { FieldName: 'Actual', FieldValue: 0 },
          { FieldName: 'ReadTime', FieldValue: 0 },
          { FieldName: 'BackTime', FieldValue: '1800-01-01T00:00:00' },
        ],
        ListData: {
          ENPSDatabase: 'svrscala-backup',
          Path: 'P_NASNEWS\\W\\R_C8E9599C-5CC9-42A0-905431F716269206',
          Guid: 'F2EA857A-6D3C-42EA-BD005DC44062A776',
          ContainerTitle: '2PM Update',
          Title: 'New Row 4 Jason Saunders',
          Type: 3,
          Priority: 0,
          Approved: false,
          OutputType: 0,
          Creator: 'J.SAUNDERS',
          ModBy: 'J.SAUNDERS',
          MosObjId: '',
          MosControl: false,
          ModTime: '2019-07-19T16:08:23Z',
          Expires: '2019-08-18T16:08:23Z',
          Owner: 'J.SAUNDERS',
          BeginText: null,
          FileStorageVersion: 0,
        },
        ObjectLinks: { LinkedRecords: { $id: '6', $values: [] } },
        SocialMediaLinks: [],
        ObjectTags: { Tags: [] },
        ChatData: [],
        IsSearchReturnedResult: false,
      },
      Float: false,
      Break: false,
      HasYellowTimingBar: false,
      CBreak: false,
      NotForBroadcast: false,
    },
    {
      CollectionsCollection: null,
      ScriptOrder: 7,
      PageNum: 'A7',
      FrontTime: '2023-12-29T19:00:42Z',
      FrontTimeFormatted: '07:00:42 PM',
      BackTime: '2023-12-29T19:05:00Z',
      BackTimeFormatted: '07:05:00 PM',
      FrontOverUnder: '-10675199.00:00:00',
      BackOverUnder: '-10675199.00:00:00',
      CumeTime: '00:00:42',
      CumeTimeFormatted: '0:42',
      BackCumeTime: '00:00:00',
      BackCumeTimeFormatted: '0:00',
      IsTimingBarSelected: false,
      IsRowFlashing: false,
      IsFrozen: false,
      RecordPointer: {
        ReadTime: 0,
        Actual: null,
        Estimated: '00:00:00',
        HardHitFront: '1800-01-01T00:00:00',
        HardHitBack: '1800-01-01T00:00:00',
        ActualTimeString: { Key: 'ReadTime', Value: '0:00' },
        DefaultLayout: null,
        Loading: false,
        ObjectProperties: [
          { FieldName: 'TextCommands', FieldValue: {} },
          { FieldName: 'Text', FieldValue: '' },
          { FieldName: 'VPContainsRTL', FieldValue: false },
          { FieldName: 'Owner', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'Creator', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'ModBy', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'AnchorTime', FieldValue: '2019-07-19T16:08:23Z' },
          { FieldName: 'Expires', FieldValue: '2019-08-18T16:08:23Z' },
          { FieldName: 'ModTime', FieldValue: '2019-07-19T16:08:23Z' },
          { FieldName: 'Type', FieldValue: 3 },
          { FieldName: 'SourceModBy', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'SourceModTime', FieldValue: '2019-07-19T16:07:19Z' },
          {
            FieldName: 'GUID',
            FieldValue: '23DBED6A-C871-4DF2-9F44E3062CA8A59D',
          },
          { FieldName: 'pubApproved', FieldValue: false },
          { FieldName: 'ScriptSubType', FieldValue: 'Broadcast' },
          { FieldName: 'Priority', FieldValue: 0 },
          { FieldName: 'Approved', FieldValue: false },
          { FieldName: 'Version', FieldValue: 0 },
          { FieldName: 'Status', FieldValue: '2' },
          { FieldName: 'WriteCount', FieldValue: 4 },
          { FieldName: 'RowModTime', FieldValue: '2023-12-29T12:00:55Z' },
          { FieldName: 'RowModBy', FieldValue: 'AutoCreate' },
          { FieldName: 'Database', FieldValue: 'svrscala-backup' },
          {
            FieldName: 'Path',
            FieldValue: 'P_NASNEWS\\W\\R_C8E9599C-5CC9-42A0-905431F716269206',
          },
          { FieldName: 'Title', FieldValue: 'New Row 5 Jason Saunders' },
          { FieldName: 'OutputType', FieldValue: 0 },
          { FieldName: 'PageNum', FieldValue: 'A7' },
          { FieldName: 'UserCanWritePermissions', FieldValue: true },
          { FieldName: 'CumeTime', FieldValue: 0 },
          { FieldName: 'DoNotArchive', FieldValue: false },
          { FieldName: 'MOSObjSlugs', FieldValue: '' },
          { FieldName: 'ObjectPlaceholderCreate', FieldValue: '' },
          { FieldName: 'MOSChannels', FieldValue: '' },
          { FieldName: 'Reporter', FieldValue: '' },
          { FieldName: 'MOSStatus', FieldValue: '' },
          { FieldName: 'Float', FieldValue: false },
          { FieldName: 'Break', FieldValue: false },
          { FieldName: 'Estimated', FieldValue: 0 },
          { FieldName: 'Actual', FieldValue: 0 },
          { FieldName: 'ReadTime', FieldValue: 0 },
          { FieldName: 'BackTime', FieldValue: '1800-01-01T00:00:00' },
        ],
        ListData: {
          ENPSDatabase: 'svrscala-backup',
          Path: 'P_NASNEWS\\W\\R_C8E9599C-5CC9-42A0-905431F716269206',
          Guid: '23DBED6A-C871-4DF2-9F44E3062CA8A59D',
          ContainerTitle: '2PM Update',
          Title: 'New Row 5 Jason Saunders',
          Type: 3,
          Priority: 0,
          Approved: false,
          OutputType: 0,
          Creator: 'J.SAUNDERS',
          ModBy: 'J.SAUNDERS',
          MosObjId: '',
          MosControl: false,
          ModTime: '2019-07-19T16:08:23Z',
          Expires: '2019-08-18T16:08:23Z',
          Owner: 'J.SAUNDERS',
          BeginText: null,
          FileStorageVersion: 0,
        },
        ObjectLinks: { LinkedRecords: { $id: '7', $values: [] } },
        SocialMediaLinks: [],
        ObjectTags: { Tags: [] },
        ChatData: [],
        IsSearchReturnedResult: false,
      },
      Float: false,
      Break: false,
      HasYellowTimingBar: false,
      CBreak: false,
      NotForBroadcast: false,
    },
    {
      CollectionsCollection: null,
      ScriptOrder: 8,
      PageNum: 'A8',
      FrontTime: '2023-12-29T19:00:42Z',
      FrontTimeFormatted: '07:00:42 PM',
      BackTime: '2023-12-29T19:05:00Z',
      BackTimeFormatted: '07:05:00 PM',
      FrontOverUnder: '-10675199.00:00:00',
      BackOverUnder: '-10675199.00:00:00',
      CumeTime: '00:00:42',
      CumeTimeFormatted: '0:42',
      BackCumeTime: '00:00:00',
      BackCumeTimeFormatted: '0:00',
      IsTimingBarSelected: false,
      IsRowFlashing: false,
      IsFrozen: false,
      RecordPointer: {
        ReadTime: 0,
        Actual: null,
        Estimated: '00:00:00',
        HardHitFront: '1800-01-01T00:00:00',
        HardHitBack: '1800-01-01T00:00:00',
        ActualTimeString: { Key: 'ReadTime', Value: '0:00' },
        DefaultLayout: null,
        Loading: false,
        ObjectProperties: [
          { FieldName: 'TextCommands', FieldValue: {} },
          { FieldName: 'Text', FieldValue: '' },
          { FieldName: 'VPContainsRTL', FieldValue: false },
          { FieldName: 'Owner', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'Creator', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'ModBy', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'AnchorTime', FieldValue: '2019-07-19T16:08:23Z' },
          { FieldName: 'Expires', FieldValue: '2019-08-18T16:08:23Z' },
          { FieldName: 'ModTime', FieldValue: '2019-07-19T16:08:23Z' },
          { FieldName: 'Type', FieldValue: 3 },
          { FieldName: 'SourceModBy', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'SourceModTime', FieldValue: '2019-07-19T16:07:24Z' },
          {
            FieldName: 'GUID',
            FieldValue: '795CDB2F-AE34-4721-A667C690617DDBBB',
          },
          { FieldName: 'pubApproved', FieldValue: false },
          { FieldName: 'ScriptSubType', FieldValue: 'Broadcast' },
          { FieldName: 'Priority', FieldValue: 0 },
          { FieldName: 'Approved', FieldValue: false },
          { FieldName: 'Version', FieldValue: 0 },
          { FieldName: 'Status', FieldValue: '2' },
          { FieldName: 'WriteCount', FieldValue: 4 },
          { FieldName: 'RowModTime', FieldValue: '2023-12-29T12:00:55Z' },
          { FieldName: 'RowModBy', FieldValue: 'AutoCreate' },
          { FieldName: 'Database', FieldValue: 'svrscala-backup' },
          {
            FieldName: 'Path',
            FieldValue: 'P_NASNEWS\\W\\R_C8E9599C-5CC9-42A0-905431F716269206',
          },
          { FieldName: 'Title', FieldValue: 'New Row 6 Jason Saunders' },
          { FieldName: 'OutputType', FieldValue: 0 },
          { FieldName: 'PageNum', FieldValue: 'A8' },
          { FieldName: 'UserCanWritePermissions', FieldValue: true },
          { FieldName: 'CumeTime', FieldValue: 0 },
          { FieldName: 'DoNotArchive', FieldValue: false },
          { FieldName: 'MOSObjSlugs', FieldValue: '' },
          { FieldName: 'ObjectPlaceholderCreate', FieldValue: '' },
          { FieldName: 'MOSChannels', FieldValue: '' },
          { FieldName: 'Reporter', FieldValue: '' },
          { FieldName: 'MOSStatus', FieldValue: '' },
          { FieldName: 'Float', FieldValue: false },
          { FieldName: 'Break', FieldValue: false },
          { FieldName: 'Estimated', FieldValue: 0 },
          { FieldName: 'Actual', FieldValue: 0 },
          { FieldName: 'ReadTime', FieldValue: 0 },
          { FieldName: 'BackTime', FieldValue: '1800-01-01T00:00:00' },
        ],
        ListData: {
          ENPSDatabase: 'svrscala-backup',
          Path: 'P_NASNEWS\\W\\R_C8E9599C-5CC9-42A0-905431F716269206',
          Guid: '795CDB2F-AE34-4721-A667C690617DDBBB',
          ContainerTitle: '2PM Update',
          Title: 'New Row 6 Jason Saunders',
          Type: 3,
          Priority: 0,
          Approved: false,
          OutputType: 0,
          Creator: 'J.SAUNDERS',
          ModBy: 'J.SAUNDERS',
          MosObjId: '',
          MosControl: false,
          ModTime: '2019-07-19T16:08:23Z',
          Expires: '2019-08-18T16:08:23Z',
          Owner: 'J.SAUNDERS',
          BeginText: null,
          FileStorageVersion: 0,
        },
        ObjectLinks: { LinkedRecords: { $id: '8', $values: [] } },
        SocialMediaLinks: [],
        ObjectTags: { Tags: [] },
        ChatData: [],
        IsSearchReturnedResult: false,
      },
      Float: false,
      Break: false,
      HasYellowTimingBar: false,
      CBreak: false,
      NotForBroadcast: false,
    },
    {
      CollectionsCollection: null,
      ScriptOrder: 9,
      PageNum: 'A9',
      FrontTime: '2023-12-29T19:00:42Z',
      FrontTimeFormatted: '07:00:42 PM',
      BackTime: '2023-12-29T19:05:00Z',
      BackTimeFormatted: '07:05:00 PM',
      FrontOverUnder: '-10675199.00:00:00',
      BackOverUnder: '-10675199.00:00:00',
      CumeTime: '00:00:42',
      CumeTimeFormatted: '0:42',
      BackCumeTime: '00:00:00',
      BackCumeTimeFormatted: '0:00',
      IsTimingBarSelected: false,
      IsRowFlashing: false,
      IsFrozen: false,
      RecordPointer: {
        ReadTime: 0,
        Actual: null,
        Estimated: '00:00:00',
        HardHitFront: '1800-01-01T00:00:00',
        HardHitBack: '1800-01-01T00:00:00',
        ActualTimeString: { Key: 'ReadTime', Value: '0:00' },
        DefaultLayout: null,
        Loading: false,
        ObjectProperties: [
          { FieldName: 'TextCommands', FieldValue: {} },
          { FieldName: 'Text', FieldValue: '' },
          { FieldName: 'VPContainsRTL', FieldValue: false },
          { FieldName: 'Owner', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'Creator', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'ModBy', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'AnchorTime', FieldValue: '2019-07-19T16:08:23Z' },
          { FieldName: 'Expires', FieldValue: '2019-08-18T16:08:23Z' },
          { FieldName: 'ModTime', FieldValue: '2019-07-19T16:08:23Z' },
          { FieldName: 'Type', FieldValue: 3 },
          { FieldName: 'SourceModBy', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'SourceModTime', FieldValue: '2019-07-19T16:07:30Z' },
          {
            FieldName: 'GUID',
            FieldValue: '53BC04FE-C094-44C5-8ECE7851E1FFB56C',
          },
          { FieldName: 'pubApproved', FieldValue: false },
          { FieldName: 'ScriptSubType', FieldValue: 'Broadcast' },
          { FieldName: 'Priority', FieldValue: 0 },
          { FieldName: 'Approved', FieldValue: false },
          { FieldName: 'Version', FieldValue: 0 },
          { FieldName: 'Status', FieldValue: '2' },
          { FieldName: 'WriteCount', FieldValue: 4 },
          { FieldName: 'RowModTime', FieldValue: '2023-12-29T12:00:55Z' },
          { FieldName: 'RowModBy', FieldValue: 'AutoCreate' },
          { FieldName: 'Database', FieldValue: 'svrscala-backup' },
          {
            FieldName: 'Path',
            FieldValue: 'P_NASNEWS\\W\\R_C8E9599C-5CC9-42A0-905431F716269206',
          },
          { FieldName: 'Title', FieldValue: 'New Row 7 Jason Saunders' },
          { FieldName: 'OutputType', FieldValue: 0 },
          { FieldName: 'PageNum', FieldValue: 'A9' },
          { FieldName: 'UserCanWritePermissions', FieldValue: true },
          { FieldName: 'CumeTime', FieldValue: 0 },
          { FieldName: 'DoNotArchive', FieldValue: false },
          { FieldName: 'MOSObjSlugs', FieldValue: '' },
          { FieldName: 'ObjectPlaceholderCreate', FieldValue: '' },
          { FieldName: 'MOSChannels', FieldValue: '' },
          { FieldName: 'Reporter', FieldValue: '' },
          { FieldName: 'MOSStatus', FieldValue: '' },
          { FieldName: 'Float', FieldValue: false },
          { FieldName: 'Break', FieldValue: false },
          { FieldName: 'Estimated', FieldValue: 0 },
          { FieldName: 'Actual', FieldValue: 0 },
          { FieldName: 'ReadTime', FieldValue: 0 },
          { FieldName: 'BackTime', FieldValue: '1800-01-01T00:00:00' },
        ],
        ListData: {
          ENPSDatabase: 'svrscala-backup',
          Path: 'P_NASNEWS\\W\\R_C8E9599C-5CC9-42A0-905431F716269206',
          Guid: '53BC04FE-C094-44C5-8ECE7851E1FFB56C',
          ContainerTitle: '2PM Update',
          Title: 'New Row 7 Jason Saunders',
          Type: 3,
          Priority: 0,
          Approved: false,
          OutputType: 0,
          Creator: 'J.SAUNDERS',
          ModBy: 'J.SAUNDERS',
          MosObjId: '',
          MosControl: false,
          ModTime: '2019-07-19T16:08:23Z',
          Expires: '2019-08-18T16:08:23Z',
          Owner: 'J.SAUNDERS',
          BeginText: null,
          FileStorageVersion: 0,
        },
        ObjectLinks: { LinkedRecords: { $id: '9', $values: [] } },
        SocialMediaLinks: [],
        ObjectTags: { Tags: [] },
        ChatData: [],
        IsSearchReturnedResult: false,
      },
      Float: false,
      Break: false,
      HasYellowTimingBar: false,
      CBreak: false,
      NotForBroadcast: false,
    },
    {
      CollectionsCollection: null,
      ScriptOrder: 10,
      PageNum: 'A10',
      FrontTime: '2023-12-29T19:00:42Z',
      FrontTimeFormatted: '07:00:42 PM',
      BackTime: '2023-12-29T19:05:00Z',
      BackTimeFormatted: '07:05:00 PM',
      FrontOverUnder: '-10675199.00:00:00',
      BackOverUnder: '-10675199.00:00:00',
      CumeTime: '00:00:42',
      CumeTimeFormatted: '0:42',
      BackCumeTime: '00:00:00',
      BackCumeTimeFormatted: '0:00',
      IsTimingBarSelected: false,
      IsRowFlashing: false,
      IsFrozen: false,
      RecordPointer: {
        ReadTime: 0,
        Actual: null,
        Estimated: '00:00:00',
        HardHitFront: '1800-01-01T00:00:00',
        HardHitBack: '1800-01-01T00:00:00',
        ActualTimeString: { Key: 'ReadTime', Value: '0:00' },
        DefaultLayout: null,
        Loading: false,
        ObjectProperties: [
          { FieldName: 'TextCommands', FieldValue: {} },
          { FieldName: 'Text', FieldValue: '' },
          { FieldName: 'VPContainsRTL', FieldValue: false },
          { FieldName: 'Owner', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'Creator', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'ModBy', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'AnchorTime', FieldValue: '2019-07-19T16:08:23Z' },
          { FieldName: 'Expires', FieldValue: '2019-08-18T16:08:23Z' },
          { FieldName: 'ModTime', FieldValue: '2019-07-19T16:08:23Z' },
          { FieldName: 'Type', FieldValue: 3 },
          { FieldName: 'SourceModBy', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'SourceModTime', FieldValue: '2019-07-19T16:07:54Z' },
          {
            FieldName: 'GUID',
            FieldValue: '89698582-7745-4389-B7BD60F49FE813C3',
          },
          { FieldName: 'pubApproved', FieldValue: false },
          { FieldName: 'ScriptSubType', FieldValue: 'Broadcast' },
          { FieldName: 'Priority', FieldValue: 0 },
          { FieldName: 'Approved', FieldValue: false },
          { FieldName: 'Version', FieldValue: 0 },
          { FieldName: 'Status', FieldValue: '2' },
          { FieldName: 'WriteCount', FieldValue: 4 },
          { FieldName: 'RowModTime', FieldValue: '2023-12-29T12:00:55Z' },
          { FieldName: 'RowModBy', FieldValue: 'AutoCreate' },
          { FieldName: 'Database', FieldValue: 'svrscala-backup' },
          {
            FieldName: 'Path',
            FieldValue: 'P_NASNEWS\\W\\R_C8E9599C-5CC9-42A0-905431F716269206',
          },
          { FieldName: 'Title', FieldValue: 'New Row 9 Jason Saunders' },
          { FieldName: 'OutputType', FieldValue: 0 },
          { FieldName: 'PageNum', FieldValue: 'A10' },
          { FieldName: 'UserCanWritePermissions', FieldValue: true },
          { FieldName: 'CumeTime', FieldValue: 0 },
          { FieldName: 'DoNotArchive', FieldValue: false },
          { FieldName: 'MOSObjSlugs', FieldValue: '' },
          { FieldName: 'ObjectPlaceholderCreate', FieldValue: '' },
          { FieldName: 'MOSChannels', FieldValue: '' },
          { FieldName: 'Reporter', FieldValue: '' },
          { FieldName: 'MOSStatus', FieldValue: '' },
          { FieldName: 'Float', FieldValue: false },
          { FieldName: 'Break', FieldValue: false },
          { FieldName: 'Estimated', FieldValue: 0 },
          { FieldName: 'Actual', FieldValue: 0 },
          { FieldName: 'ReadTime', FieldValue: 0 },
          { FieldName: 'BackTime', FieldValue: '1800-01-01T00:00:00' },
        ],
        ListData: {
          ENPSDatabase: 'svrscala-backup',
          Path: 'P_NASNEWS\\W\\R_C8E9599C-5CC9-42A0-905431F716269206',
          Guid: '89698582-7745-4389-B7BD60F49FE813C3',
          ContainerTitle: '2PM Update',
          Title: 'New Row 9 Jason Saunders',
          Type: 3,
          Priority: 0,
          Approved: false,
          OutputType: 0,
          Creator: 'J.SAUNDERS',
          ModBy: 'J.SAUNDERS',
          MosObjId: '',
          MosControl: false,
          ModTime: '2019-07-19T16:08:23Z',
          Expires: '2019-08-18T16:08:23Z',
          Owner: 'J.SAUNDERS',
          BeginText: null,
          FileStorageVersion: 0,
        },
        ObjectLinks: { LinkedRecords: { $id: '10', $values: [] } },
        SocialMediaLinks: [],
        ObjectTags: { Tags: [] },
        ChatData: [],
        IsSearchReturnedResult: false,
      },
      Float: false,
      Break: false,
      HasYellowTimingBar: false,
      CBreak: false,
      NotForBroadcast: false,
    },
    {
      CollectionsCollection: null,
      ScriptOrder: 11,
      PageNum: 'A11',
      FrontTime: '2023-12-29T19:00:42Z',
      FrontTimeFormatted: '07:00:42 PM',
      BackTime: '2023-12-29T19:05:00Z',
      BackTimeFormatted: '07:05:00 PM',
      FrontOverUnder: '-10675199.00:00:00',
      BackOverUnder: '-10675199.00:00:00',
      CumeTime: '00:00:42',
      CumeTimeFormatted: '0:42',
      BackCumeTime: '00:00:00',
      BackCumeTimeFormatted: '0:00',
      IsTimingBarSelected: false,
      IsRowFlashing: false,
      IsFrozen: false,
      RecordPointer: {
        ReadTime: 0,
        Actual: null,
        Estimated: '00:00:00',
        HardHitFront: '1800-01-01T00:00:00',
        HardHitBack: '1800-01-01T00:00:00',
        ActualTimeString: { Key: 'ReadTime', Value: '0:00' },
        DefaultLayout: null,
        Loading: false,
        ObjectProperties: [
          { FieldName: 'TextCommands', FieldValue: {} },
          { FieldName: 'Text', FieldValue: '' },
          { FieldName: 'VPContainsRTL', FieldValue: false },
          { FieldName: 'Owner', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'Creator', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'ModBy', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'AnchorTime', FieldValue: '2019-07-19T16:08:23Z' },
          { FieldName: 'Expires', FieldValue: '2019-08-18T16:08:23Z' },
          { FieldName: 'ModTime', FieldValue: '2019-07-19T16:08:23Z' },
          { FieldName: 'Type', FieldValue: 3 },
          { FieldName: 'SourceModBy', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'SourceModTime', FieldValue: '2019-07-19T16:07:44Z' },
          {
            FieldName: 'GUID',
            FieldValue: 'EBF30A97-FFDC-48B7-A04AE0CF906C2927',
          },
          { FieldName: 'pubApproved', FieldValue: false },
          { FieldName: 'ScriptSubType', FieldValue: 'Broadcast' },
          { FieldName: 'Priority', FieldValue: 0 },
          { FieldName: 'Approved', FieldValue: false },
          { FieldName: 'Version', FieldValue: 0 },
          { FieldName: 'Status', FieldValue: '2' },
          { FieldName: 'WriteCount', FieldValue: 4 },
          { FieldName: 'RowModTime', FieldValue: '2023-12-29T12:00:55Z' },
          { FieldName: 'RowModBy', FieldValue: 'AutoCreate' },
          { FieldName: 'Database', FieldValue: 'svrscala-backup' },
          {
            FieldName: 'Path',
            FieldValue: 'P_NASNEWS\\W\\R_C8E9599C-5CC9-42A0-905431F716269206',
          },
          { FieldName: 'Title', FieldValue: 'New Row 8 Jason Saunders' },
          { FieldName: 'OutputType', FieldValue: 0 },
          { FieldName: 'PageNum', FieldValue: 'A11' },
          { FieldName: 'UserCanWritePermissions', FieldValue: true },
          { FieldName: 'CumeTime', FieldValue: 0 },
          { FieldName: 'DoNotArchive', FieldValue: false },
          { FieldName: 'MOSObjSlugs', FieldValue: '' },
          { FieldName: 'ObjectPlaceholderCreate', FieldValue: '' },
          { FieldName: 'MOSChannels', FieldValue: '' },
          { FieldName: 'Reporter', FieldValue: '' },
          { FieldName: 'MOSStatus', FieldValue: '' },
          { FieldName: 'Float', FieldValue: false },
          { FieldName: 'Break', FieldValue: false },
          { FieldName: 'Estimated', FieldValue: 0 },
          { FieldName: 'Actual', FieldValue: 0 },
          { FieldName: 'ReadTime', FieldValue: 0 },
          { FieldName: 'BackTime', FieldValue: '1800-01-01T00:00:00' },
        ],
        ListData: {
          ENPSDatabase: 'svrscala-backup',
          Path: 'P_NASNEWS\\W\\R_C8E9599C-5CC9-42A0-905431F716269206',
          Guid: 'EBF30A97-FFDC-48B7-A04AE0CF906C2927',
          ContainerTitle: '2PM Update',
          Title: 'New Row 8 Jason Saunders',
          Type: 3,
          Priority: 0,
          Approved: false,
          OutputType: 0,
          Creator: 'J.SAUNDERS',
          ModBy: 'J.SAUNDERS',
          MosObjId: '',
          MosControl: false,
          ModTime: '2019-07-19T16:08:23Z',
          Expires: '2019-08-18T16:08:23Z',
          Owner: 'J.SAUNDERS',
          BeginText: null,
          FileStorageVersion: 0,
        },
        ObjectLinks: { LinkedRecords: { $id: '11', $values: [] } },
        SocialMediaLinks: [],
        ObjectTags: { Tags: [] },
        ChatData: [],
        IsSearchReturnedResult: false,
      },
      Float: false,
      Break: false,
      HasYellowTimingBar: false,
      CBreak: false,
      NotForBroadcast: false,
    },
    {
      CollectionsCollection: null,
      ScriptOrder: 12,
      PageNum: 'A12',
      FrontTime: '2023-12-29T19:00:42Z',
      FrontTimeFormatted: '07:00:42 PM',
      BackTime: '2023-12-29T19:05:00Z',
      BackTimeFormatted: '07:05:00 PM',
      FrontOverUnder: '-10675199.00:00:00',
      BackOverUnder: '-10675199.00:00:00',
      CumeTime: '00:00:42',
      CumeTimeFormatted: '0:42',
      BackCumeTime: '00:00:00',
      BackCumeTimeFormatted: '0:00',
      IsTimingBarSelected: false,
      IsRowFlashing: false,
      IsFrozen: false,
      RecordPointer: {
        ReadTime: 0,
        Actual: null,
        Estimated: '00:00:00',
        HardHitFront: '1800-01-01T00:00:00',
        HardHitBack: '1800-01-01T00:00:00',
        ActualTimeString: { Key: 'ReadTime', Value: '0:00' },
        DefaultLayout: null,
        Loading: false,
        ObjectProperties: [
          { FieldName: 'TextCommands', FieldValue: {} },
          { FieldName: 'Text', FieldValue: '' },
          { FieldName: 'VPContainsRTL', FieldValue: false },
          { FieldName: 'Owner', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'Creator', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'ModBy', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'AnchorTime', FieldValue: '2019-07-19T16:08:23Z' },
          { FieldName: 'Expires', FieldValue: '2019-08-18T16:08:23Z' },
          { FieldName: 'ModTime', FieldValue: '2019-07-19T16:08:23Z' },
          { FieldName: 'Type', FieldValue: 3 },
          { FieldName: 'SourceModBy', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'SourceModTime', FieldValue: '2019-07-19T16:07:57Z' },
          {
            FieldName: 'GUID',
            FieldValue: '01840C35-ED9D-4F3E-92188F5911C592DF',
          },
          { FieldName: 'pubApproved', FieldValue: false },
          { FieldName: 'ScriptSubType', FieldValue: 'Broadcast' },
          { FieldName: 'Priority', FieldValue: 0 },
          { FieldName: 'Approved', FieldValue: false },
          { FieldName: 'Version', FieldValue: 0 },
          { FieldName: 'Status', FieldValue: '2' },
          { FieldName: 'WriteCount', FieldValue: 4 },
          { FieldName: 'RowModTime', FieldValue: '2023-12-29T12:00:55Z' },
          { FieldName: 'RowModBy', FieldValue: 'AutoCreate' },
          { FieldName: 'Database', FieldValue: 'svrscala-backup' },
          {
            FieldName: 'Path',
            FieldValue: 'P_NASNEWS\\W\\R_C8E9599C-5CC9-42A0-905431F716269206',
          },
          { FieldName: 'Title', FieldValue: 'New Row 10 Jason Saunders' },
          { FieldName: 'OutputType', FieldValue: 0 },
          { FieldName: 'PageNum', FieldValue: 'A12' },
          { FieldName: 'UserCanWritePermissions', FieldValue: true },
          { FieldName: 'CumeTime', FieldValue: 0 },
          { FieldName: 'DoNotArchive', FieldValue: false },
          { FieldName: 'MOSObjSlugs', FieldValue: '' },
          { FieldName: 'ObjectPlaceholderCreate', FieldValue: '' },
          { FieldName: 'MOSChannels', FieldValue: '' },
          { FieldName: 'Reporter', FieldValue: '' },
          { FieldName: 'MOSStatus', FieldValue: '' },
          { FieldName: 'Float', FieldValue: false },
          { FieldName: 'Break', FieldValue: false },
          { FieldName: 'Estimated', FieldValue: 0 },
          { FieldName: 'Actual', FieldValue: 0 },
          { FieldName: 'ReadTime', FieldValue: 0 },
          { FieldName: 'BackTime', FieldValue: '1800-01-01T00:00:00' },
        ],
        ListData: {
          ENPSDatabase: 'svrscala-backup',
          Path: 'P_NASNEWS\\W\\R_C8E9599C-5CC9-42A0-905431F716269206',
          Guid: '01840C35-ED9D-4F3E-92188F5911C592DF',
          ContainerTitle: '2PM Update',
          Title: 'New Row 10 Jason Saunders',
          Type: 3,
          Priority: 0,
          Approved: false,
          OutputType: 0,
          Creator: 'J.SAUNDERS',
          ModBy: 'J.SAUNDERS',
          MosObjId: '',
          MosControl: false,
          ModTime: '2019-07-19T16:08:23Z',
          Expires: '2019-08-18T16:08:23Z',
          Owner: 'J.SAUNDERS',
          BeginText: null,
          FileStorageVersion: 0,
        },
        ObjectLinks: { LinkedRecords: { $id: '12', $values: [] } },
        SocialMediaLinks: [],
        ObjectTags: { Tags: [] },
        ChatData: [],
        IsSearchReturnedResult: false,
      },
      Float: false,
      Break: false,
      HasYellowTimingBar: false,
      CBreak: false,
      NotForBroadcast: false,
    },
    {
      CollectionsCollection: null,
      ScriptOrder: 13,
      PageNum: null,
      FrontTime: '0001-01-01T00:00:00',
      FrontTimeFormatted: '12:00:00 AM',
      BackTime: '0001-01-01T00:00:00',
      BackTimeFormatted: '12:00:00 AM',
      FrontOverUnder: '00:00:00',
      BackOverUnder: '00:00:00',
      CumeTime: '00:00:00',
      CumeTimeFormatted: '0:00',
      BackCumeTime: '00:00:00',
      BackCumeTimeFormatted: '0:00',
      IsTimingBarSelected: false,
      IsRowFlashing: false,
      IsFrozen: false,
      RecordPointer: {
        ReadTime: 0,
        Actual: null,
        Estimated: '00:00:00',
        HardHitFront: '1800-01-01T00:00:00',
        HardHitBack: '1800-01-01T00:00:00',
        ActualTimeString: { Key: 'ReadTime', Value: '0:00' },
        DefaultLayout: null,
        Loading: false,
        ObjectProperties: [
          { FieldName: 'Guid', FieldValue: '0' },
          { FieldName: 'UserCanWritePermissions', FieldValue: true },
          { FieldName: 'CumeTime', FieldValue: 0 },
          { FieldName: 'DoNotArchive', FieldValue: false },
          { FieldName: 'MOSObjSlugs', FieldValue: '' },
          { FieldName: 'ObjectPlaceholderCreate', FieldValue: '' },
          { FieldName: 'MOSChannels', FieldValue: '' },
          { FieldName: 'Reporter', FieldValue: '' },
          { FieldName: 'MOSStatus', FieldValue: '' },
          { FieldName: 'Float', FieldValue: false },
          { FieldName: 'ModBy', FieldValue: '' },
          { FieldName: 'Break', FieldValue: false },
          { FieldName: 'Approved', FieldValue: false },
          { FieldName: 'Estimated', FieldValue: 0 },
          { FieldName: 'Actual', FieldValue: 0 },
          { FieldName: 'ReadTime', FieldValue: 0 },
          { FieldName: 'BackTime', FieldValue: '1800-01-01T00:00:00' },
        ],
        ListData: {
          ENPSDatabase: '',
          Path: '',
          Guid: '0',
          ContainerTitle: null,
          Title: '',
          Type: 0,
          Priority: 0,
          Approved: false,
          OutputType: 0,
          Creator: null,
          ModBy: null,
          MosObjId: '',
          MosControl: false,
          ModTime: '0001-01-01T00:00:00',
          Expires: '0001-01-01T00:00:00',
          Owner: null,
          BeginText: null,
          FileStorageVersion: 0,
        },
        ObjectLinks: { LinkedRecords: { $id: '13', $values: [] } },
        SocialMediaLinks: [],
        ObjectTags: { Tags: [] },
        ChatData: [],
        IsSearchReturnedResult: false,
      },
      Float: false,
      Break: false,
      HasYellowTimingBar: false,
      CBreak: false,
      NotForBroadcast: false,
    },
  ],
  UpdatesSuspended: false,
  SuspendRowFlashing: false,
  HasPendingChanges: false,
  OnAir: false,
  LTTRecording: false,
  TimeFormat: 0,
  DefaultLayout: {
    DefaultLayout: [
      {
        ColumnName: 'PageNum',
        ColumnWidth: 600,
        ColumnDisplayName: 'Page',
        ColumnWordWrap: false,
        ColumnAutoSizeWidth: false,
        ColumnJustification: 'Left',
        ColumnValidation: 'Text',
        ColumnList: '',
        IsReadOnly: false,
        SortOrder: 0,
        ColumnMaxLen: '5',
        ColumnExtractTarget: false,
      },
      {
        ColumnName: 'RowStatus',
        ColumnWidth: 150,
        ColumnDisplayName: '',
        ColumnWordWrap: false,
        ColumnAutoSizeWidth: false,
        ColumnJustification: 'Left',
        ColumnValidation: 'Text',
        ColumnList: '',
        IsReadOnly: true,
        SortOrder: 1,
        ColumnMaxLen: '',
        ColumnExtractTarget: false,
      },
      {
        ColumnName: 'Slug',
        ColumnWidth: 2790,
        ColumnDisplayName: 'Story Slug',
        ColumnWordWrap: false,
        ColumnAutoSizeWidth: false,
        ColumnJustification: 'Left',
        ColumnValidation: 'Text',
        ColumnList: '',
        IsReadOnly: false,
        SortOrder: 2,
        ColumnMaxLen: '',
        ColumnExtractTarget: false,
      },
      {
        ColumnName: 'SegStatus',
        ColumnWidth: 210,
        ColumnDisplayName: '',
        ColumnWordWrap: false,
        ColumnAutoSizeWidth: false,
        ColumnJustification: 'Left',
        ColumnValidation: 'Text',
        ColumnList: '',
        IsReadOnly: true,
        SortOrder: 3,
        ColumnMaxLen: '',
        ColumnExtractTarget: false,
      },
      {
        ColumnName: 'Segment',
        ColumnWidth: 915,
        ColumnDisplayName: 'Segment',
        ColumnWordWrap: false,
        ColumnAutoSizeWidth: false,
        ColumnJustification: 'Left',
        ColumnValidation: 'Text',
        ColumnList: '',
        IsReadOnly: false,
        SortOrder: 4,
        ColumnMaxLen: '',
        ColumnExtractTarget: false,
      },
      {
        ColumnName: 'CumeTime',
        ColumnWidth: 1005,
        ColumnDisplayName: 'Cume',
        ColumnWordWrap: false,
        ColumnAutoSizeWidth: false,
        ColumnJustification: 'Right',
        ColumnValidation: 'Duration',
        ColumnList: '',
        IsReadOnly: true,
        SortOrder: 5,
        ColumnMaxLen: '',
        ColumnExtractTarget: false,
      },
      {
        ColumnName: 'DoNotArchive',
        ColumnWidth: 1000,
        ColumnDisplayName: 'DoNotArchive',
        ColumnWordWrap: false,
        ColumnAutoSizeWidth: false,
        ColumnJustification: 'Left',
        ColumnValidation: 'CheckBox',
        ColumnList: '',
        IsReadOnly: false,
        SortOrder: 6,
        ColumnMaxLen: '0',
        ColumnExtractTarget: false,
      },
      {
        ColumnName: 'MOSObjSlugs',
        ColumnWidth: 3855,
        ColumnDisplayName: 'MOS Obj Slug',
        ColumnWordWrap: true,
        ColumnAutoSizeWidth: true,
        ColumnJustification: 'Left',
        ColumnValidation: 'Text',
        ColumnList: '',
        IsReadOnly: true,
        SortOrder: 7,
        ColumnMaxLen: '',
        ColumnExtractTarget: false,
      },
      {
        ColumnName: 'ObjectPlaceholderCreate',
        ColumnWidth: 1005,
        ColumnDisplayName: 'Object Placeholder Create',
        ColumnWordWrap: false,
        ColumnAutoSizeWidth: false,
        ColumnJustification: 'Left',
        ColumnValidation: 'Table',
        ColumnList: 'group1|group2|group3',
        IsReadOnly: false,
        SortOrder: 8,
        ColumnMaxLen: '',
        ColumnExtractTarget: false,
      },
      {
        ColumnName: 'MOSChannels',
        ColumnWidth: 1275,
        ColumnDisplayName: 'MOS Channels',
        ColumnWordWrap: true,
        ColumnAutoSizeWidth: false,
        ColumnJustification: 'Left',
        ColumnValidation: 'MOSAutomation',
        ColumnList: '',
        IsReadOnly: false,
        SortOrder: 9,
        ColumnMaxLen: '',
        ColumnExtractTarget: false,
      },
      {
        ColumnName: 'Reporter',
        ColumnWidth: 1005,
        ColumnDisplayName: 'Reporter',
        ColumnWordWrap: false,
        ColumnAutoSizeWidth: false,
        ColumnJustification: 'Left',
        ColumnValidation: 'Text',
        ColumnList: '',
        IsReadOnly: false,
        SortOrder: 10,
        ColumnMaxLen: '0',
        ColumnExtractTarget: false,
      },
      {
        ColumnName: 'MOSStatus',
        ColumnWidth: 1575,
        ColumnDisplayName: 'MOS Status',
        ColumnWordWrap: true,
        ColumnAutoSizeWidth: true,
        ColumnJustification: 'Left',
        ColumnValidation: 'Text',
        ColumnList: '',
        IsReadOnly: true,
        SortOrder: 11,
        ColumnMaxLen: '',
        ColumnExtractTarget: false,
      },
      {
        ColumnName: 'Float',
        ColumnWidth: 600,
        ColumnDisplayName: 'Float',
        ColumnWordWrap: false,
        ColumnAutoSizeWidth: false,
        ColumnJustification: 'Center',
        ColumnValidation: 'CheckBox',
        ColumnList: '',
        IsReadOnly: false,
        SortOrder: 12,
        ColumnMaxLen: '',
        ColumnExtractTarget: false,
      },
      {
        ColumnName: 'ModBy',
        ColumnWidth: 1200,
        ColumnDisplayName: 'Last Mod By',
        ColumnWordWrap: false,
        ColumnAutoSizeWidth: false,
        ColumnJustification: 'Left',
        ColumnValidation: 'Text',
        ColumnList: '',
        IsReadOnly: true,
        SortOrder: 13,
        ColumnMaxLen: '',
        ColumnExtractTarget: false,
      },
      {
        ColumnName: 'Break',
        ColumnWidth: 600,
        ColumnDisplayName: 'Break',
        ColumnWordWrap: false,
        ColumnAutoSizeWidth: false,
        ColumnJustification: 'Center',
        ColumnValidation: 'CheckBox',
        ColumnList: '',
        IsReadOnly: false,
        SortOrder: 14,
        ColumnMaxLen: '',
        ColumnExtractTarget: false,
      },
      {
        ColumnName: 'Approved',
        ColumnWidth: 600,
        ColumnDisplayName: 'Final Appr',
        ColumnWordWrap: false,
        ColumnAutoSizeWidth: false,
        ColumnJustification: 'Center',
        ColumnValidation: 'CheckBox',
        ColumnList: '',
        IsReadOnly: false,
        SortOrder: 15,
        ColumnMaxLen: '',
        ColumnExtractTarget: false,
      },
      {
        ColumnName: 'Estimated',
        ColumnWidth: 840,
        ColumnDisplayName: 'Est Duration',
        ColumnWordWrap: false,
        ColumnAutoSizeWidth: false,
        ColumnJustification: 'Right',
        ColumnValidation: 'Duration',
        ColumnList: '',
        IsReadOnly: false,
        SortOrder: 16,
        ColumnMaxLen: '',
        ColumnExtractTarget: false,
      },
      {
        ColumnName: 'Actual',
        ColumnWidth: 720,
        ColumnDisplayName: 'Actual',
        ColumnWordWrap: false,
        ColumnAutoSizeWidth: false,
        ColumnJustification: 'Right',
        ColumnValidation: 'Duration',
        ColumnList: '',
        IsReadOnly: false,
        SortOrder: 17,
        ColumnMaxLen: '',
        ColumnExtractTarget: false,
      },
      {
        ColumnName: 'BackTime',
        ColumnWidth: 1005,
        ColumnDisplayName: 'Back',
        ColumnWordWrap: false,
        ColumnAutoSizeWidth: false,
        ColumnJustification: 'Right',
        ColumnValidation: 'Time',
        ColumnList: '',
        IsReadOnly: true,
        SortOrder: 18,
        ColumnMaxLen: '',
        ColumnExtractTarget: false,
      },
    ],
    DefaultLayoutType: 5,
  },
  Loading: false,
  ObjectProperties: [
    {
      FieldName: 'Sequence',
      FieldValue: [
        'A2021AB6-EC3D-4E5C-9B3A52C8A40D8642',
        '967C6254-BBE5-4182-8ED6E22E92CEBDD9',
        '883D6ED5-10B2-4096-9479316D9CC97F22',
        '5B505340-8D9B-46BB-AF596118684DE08D',
        'B34B5A74-77D8-42A7-94B8549898650F4F',
        'F2EA857A-6D3C-42EA-BD005DC44062A776',
        '23DBED6A-C871-4DF2-9F44E3062CA8A59D',
        '795CDB2F-AE34-4721-A667C690617DDBBB',
        '53BC04FE-C094-44C5-8ECE7851E1FFB56C',
        '89698582-7745-4389-B7BD60F49FE813C3',
        'EBF30A97-FFDC-48B7-A04AE0CF906C2927',
        '01840C35-ED9D-4F3E-92188F5911C592DF',
        '0',
      ],
    },
    { FieldName: 'Type', FieldValue: 2 },
    { FieldName: 'pubApproved', FieldValue: false },
    { FieldName: 'AnchorTime', FieldValue: '2023-12-29T19:00:00Z' },
    { FieldName: 'LocalStartTime', FieldValue: '2023-12-29T14:00:00-05:00' },
    { FieldName: 'StartTime', FieldValue: '2023-12-29T19:00:00Z' },
    { FieldName: 'Expires', FieldValue: '2024-01-28T19:00:00Z' },
    { FieldName: 'ModTime', FieldValue: '2023-12-29T19:00:00Z' },
    { FieldName: 'EndTime', FieldValue: '2023-12-29T19:05:00Z' },
    { FieldName: 'FixedDuration', FieldValue: true },
    { FieldName: 'RundownDuration', FieldValue: '5:00' },
    { FieldName: 'SortScriptTemplates', FieldValue: '0' },
    { FieldName: 'MOSroEdStart', FieldValue: '2023-12-29T19:00:00Z' },
    { FieldName: 'MOSroEdDur', FieldValue: '00:05:00' },
    { FieldName: 'GUID', FieldValue: 'C8E9599C-5CC9-42A0-905431F716269206' },
    { FieldName: 'AutoCreateDays', FieldValue: '1;2;3;4;5' },
    { FieldName: 'AutoCreateTime', FieldValue: '1899-12-30T12:00:00Z' },
    { FieldName: 'AutoArchive', FieldValue: true },
    { FieldName: 'Creator', FieldValue: 'AutoCreate' },
    { FieldName: 'Owner', FieldValue: 'AutoCreate' },
    { FieldName: 'ModBy', FieldValue: 'AutoCreate' },
    { FieldName: 'ROSubType', FieldValue: 'Broadcast' },
    { FieldName: 'Priority', FieldValue: 0 },
    { FieldName: 'Version', FieldValue: 0 },
    { FieldName: 'Status', FieldValue: '2' },
    { FieldName: 'WriteCount', FieldValue: 1442 },
    { FieldName: 'RowModTime', FieldValue: '2023-12-29T18:29:49Z' },
    {
      FieldName: 'Layout',
      FieldValue:
        'PageNum\t600\r\nRowStatus\t150\r\nSlug\t2790\r\nSegStatus\t210\r\nSegment\t915\r\nCumeTime\t1005\r\nDoNotArchive\t1000\r\nMOSObjSlugs\t3855\r\nObjectPlaceholderCreate\t1005\r\nMOSChannels\t1275\r\nReporter\t1005\r\nMOSStatus\t1575\r\nFloat\t600\r\nModBy\t1200\r\nBreak\t600\r\nApproved\t600\r\nEstimated\t840\r\nActual\t720\r\nBackTime\t1005',
    },
    { FieldName: 'AutoCreateDate', FieldValue: '20231229120001' },
    { FieldName: 'MOSControl', FieldValue: true },
    {
      FieldName: 'LastCreatedRO',
      FieldValue:
        'SVRSCALA-BACKUP;P_NASNEWS\\W;F9114187-6CF7-4929-BC673F4A2B79E2C5',
    },
    { FieldName: 'RowModBy', FieldValue: 'L.DAVIS' },
    {
      FieldName: 'MOSIDTable',
      FieldValue:
        'A2021AB6-EC3D-4E5C-9B3A52C8A40D8642=zns.precis1.nassau.mos\u0010B34B5A74-77D8-42A7-94B8549898650F4F=zns.precis1.nassau.mos',
    },
    {
      FieldName: 'MOSStorySendTargets',
      FieldValue: [
        {
          MOSID: 'harris.mplm.mos',
          StartTime: '1800-01-01T00:00:00',
          IsChecked: true,
        },
        {
          MOSID: 'PROMPTER',
          StartTime: '1800-01-01T00:00:00',
          IsChecked: true,
        },
        {
          MOSID: 'zns.precis1.nassau.mos',
          StartTime: '1800-01-01T00:00:00',
          IsChecked: true,
        },
        { MOSID: '', StartTime: '1800-01-01T00:00:00Z', IsChecked: false },
      ],
    },
    { FieldName: 'Database', FieldValue: 'svrscala-backup' },
    { FieldName: 'Path', FieldValue: 'P_NASNEWS\\W' },
    { FieldName: 'Title', FieldValue: '2PM Update' },
    { FieldName: 'OutputType', FieldValue: 0 },
    { FieldName: 'HitTime', FieldValue: '1800-01-01T00:00:00' },
    { FieldName: 'CurrentID', FieldValue: '' },
    { FieldName: 'OnAir', FieldValue: false },
    { FieldName: 'LTTRecording', FieldValue: false },
    { FieldName: 'LTTPaused', FieldValue: false },
    { FieldName: 'UserCanWritePermissions', FieldValue: true },
    { FieldName: 'UserRDScriptPermissions', FieldValue: 3 },
  ],
  ListData: {
    ENPSDatabase: 'svrscala-backup',
    Path: 'P_NASNEWS\\W',
    Guid: 'C8E9599C-5CC9-42A0-905431F716269206',
    ContainerTitle: null,
    Title: '2PM Update',
    Type: 2,
    Priority: 0,
    Approved: false,
    OutputType: 0,
    Creator: 'AutoCreate',
    ModBy: 'AutoCreate',
    MosObjId: '',
    MosControl: true,
    ModTime: '2023-12-29T19:00:00Z',
    Expires: '2024-01-28T19:00:00Z',
    Owner: 'AutoCreate',
    BeginText: null,
    FileStorageVersion: 0,
  },
  ObjectLinks: { LinkedRecords: { $id: '14', $values: [] } },
  SocialMediaLinks: [],
  ObjectTags: { Tags: [] },
  ChatData: [],
  IsSearchReturnedResult: false,
}
