import { RawRundownData } from './enps-interface'

export const rawRundown5: RawRundownData = {
  TimingObj: {
    TotalCumeTime: 46,
    TotalOverUnderTime: 46,
    IsTiming: false,
    SegmentCountDown: '00:00:00',
    SegmentCountUp: '00:00:00',
    StoryCountDown: '00:00:00',
    ProgramCountDown: '00:00:00',
    FrontOverUnder: '-10675199.00:00:00',
    OverUnder: '-00:04:14',
    IsROCountDown: false,
    IsStoryCountDown: false,
    IsSegCountDown: false,
    IsROTimeEstimated: false,
  },
  CollectionScripts: [
    {
      CollectionsCollection: null,
      ScriptOrder: 1,
      PageNum: 'A1',
      FrontTime: '2023-12-28T19:00:00Z',
      FrontTimeFormatted: '07:00:00 PM',
      BackTime: '2023-12-28T19:04:14Z',
      BackTimeFormatted: '07:04:14 PM',
      FrontOverUnder: '-10675199.00:00:00',
      BackOverUnder: '-10675199.00:00:00',
      CumeTime: '00:00:00',
      CumeTimeFormatted: '0:00',
      BackCumeTime: '00:00:46',
      BackCumeTimeFormatted: '0:46',
      IsTimingBarSelected: false,
      IsRowFlashing: false,
      IsFrozen: false,
      RecordPointer: {
        ReadTime: 0,
        Actual: null,
        Estimated: '00:00:00',
        HardHitFront: '1800-01-01T00:00:00',
        HardHitBack: '1800-01-01T00:00:00',
        ActualTimeString: { Key: 'ReadTime', Value: '0:00' },
        DefaultLayout: null,
        Loading: false,
        ObjectProperties: [
          {
            FieldName: 'TextCommands',
            FieldValue: {
              '7dde9a2a-230a-4b36-a073-da7ce4d52643':
                '[<mos><itemID>2</itemID><itemSlug>Z INTRO 2PM UPDATE-SOT</itemSlug><objID>50b1c68e-fa17-4927-985b-c59cc215e20a</objID><mosID>zns.precis1.nassau.mos</mosID><mosAbstract>Z INTRO 2PM UPDATE-SOT_NEWSEDIT-C_Admin_20221007_125913.mxf</mosAbstract><objDur>687</objDur><objTB>60</objTB><objSlug>Z INTRO 2PM UPDATE-SOT_NEWSEDIT-C_Admin_20221007_125913.mxf</objSlug><objType>VIDEO</objType><itemChannel>A</itemChannel><itemEdStart>0</itemEdStart><itemEdDur>0</itemEdDur><objAir>NOT READY</objAir><objPaths><objPath>https://ZNS-BCCS01.znsbahamas.com:10456/broadcast/50b1c68e-fa17-4927-985b-c59cc215e20a.mxf</objPath><objProxyPath techDescription="Proxy">https://ZNS-BCCS01.znsbahamas.com:10456/proxy/50b1c68e-fa17-4927-985b-c59cc215e20aProxy.mp4</objProxyPath><objProxyPath techDescription="JPG">https://ZNS-BCCS01.znsbahamas.com:10456/still/50b1c68e-fa17-4927-985b-c59cc215e20a.jpg</objProxyPath></objPaths><mosExternalMetadata><mosScope>STORY</mosScope><mosSchema>http://bitcentral.com/schemas/mos/2.0</mosSchema><mosPayload/></mosExternalMetadata></mos>]',
            },
          },
          {
            FieldName: 'Text',
            FieldValue:
              '<html xmlns="http://www.w3.org/1999/xhtml">\r\n<head><title></title></head>\r\n<body><br /><span class="MOS-zns.precis1.nassau.mos" id="7dde9a2a-230a-4b36-a073-da7ce4d52643"></span><br /></body></html>',
          },
          { FieldName: 'VPContainsRTL', FieldValue: false },
          { FieldName: 'Type', FieldValue: 3 },
          { FieldName: 'Owner', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'Creator', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'AnchorTime', FieldValue: '2022-10-06T15:21:38Z' },
          { FieldName: 'Approved', FieldValue: false },
          { FieldName: 'pubApproved', FieldValue: false },
          {
            FieldName: 'GUID',
            FieldValue: '6141794A-A342-4D6A-A26C90A0639CA9F7',
          },
          { FieldName: 'Expires', FieldValue: '2022-11-11T20:11:32Z' },
          { FieldName: 'ModTime', FieldValue: '2022-10-12T19:11:32Z' },
          { FieldName: 'Priority', FieldValue: 0 },
          { FieldName: 'Version', FieldValue: 2 },
          { FieldName: 'Status', FieldValue: '3' },
          { FieldName: 'WriteCount', FieldValue: 18 },
          { FieldName: 'RowModTime', FieldValue: '2023-12-29T12:00:59Z' },
          { FieldName: 'ScriptSubType', FieldValue: 'Broadcast' },
          { FieldName: 'LastMOSItemID', FieldValue: '2' },
          { FieldName: 'ReadTime', FieldValue: 0 },
          { FieldName: 'MediaTime', FieldValue: '00:00:00' },
          { FieldName: 'TextTime', FieldValue: '00:00:00' },
          { FieldName: 'SourceReadTime', FieldValue: 0 },
          { FieldName: 'SourceMediaTime', FieldValue: '00:00:00' },
          { FieldName: 'SourceTextTime', FieldValue: '00:00:00' },
          { FieldName: 'MOSIDs', FieldValue: 'zns.precis1.nassau.mos' },
          {
            FieldName: 'MOSObjIDs',
            FieldValue: '50b1c68e-fa17-4927-985b-c59cc215e20a',
          },
          { FieldName: 'MOSSlugs', FieldValue: 'Z INTRO 2PM UPDATE-SOT' },
          { FieldName: 'MOSItemDurations', FieldValue: '0:11' },
          {
            FieldName: 'MOSAbstracts',
            FieldValue:
              'Z INTRO 2PM UPDATE-SOT_NEWSEDIT-C_Admin_20221007_125913.mxf',
          },
          {
            FieldName: 'MOSObjSlugs',
            FieldValue:
              'Z INTRO 2PM UPDATE-SOT_NEWSEDIT-C_Admin_20221007_125913.mxf',
          },
          { FieldName: 'MOSItemIDs', FieldValue: '2' },
          { FieldName: 'MOSStatus', FieldValue: 'Linked' },
          { FieldName: 'MOSTimes', FieldValue: '7:00:59 AM' },
          { FieldName: 'MOSChannels', FieldValue: ['A'] },
          { FieldName: 'MOSItemEdDurations', FieldValue: '0:00' },
          {
            FieldName: 'MOSItemPaths',
            FieldValue:
              '<objPath>https://ZNS-BCCS01.znsbahamas.com:10456/broadcast/50b1c68e-fa17-4927-985b-c59cc215e20a.mxf</objPath><objProxyPath techDescription="Proxy">https://ZNS-BCCS01.znsbahamas.com:10456/proxy/50b1c68e-fa17-4927-985b-c59cc215e20aProxy.mp4</objProxyPath><objProxyPath techDescription="JPG">https://ZNS-BCCS01.znsbahamas.com:10456/still/50b1c68e-fa17-4927-985b-c59cc215e20a.jpg</objProxyPath>',
          },
          {
            FieldName: 'MOSItemPathsBBL',
            FieldValue:
              '<objPath>https://ZNS-BCCS01.znsbahamas.com:10456/broadcast/50b1c68e-fa17-4927-985b-c59cc215e20a.mxf</objPath><objProxyPath techDescription="Proxy">https://ZNS-BCCS01.znsbahamas.com:10456/proxy/50b1c68e-fa17-4927-985b-c59cc215e20aProxy.mp4</objProxyPath><objProxyPath techDescription="JPG">https://ZNS-BCCS01.znsbahamas.com:10456/still/50b1c68e-fa17-4927-985b-c59cc215e20a.jpg</objProxyPath>',
          },
          { FieldName: 'MOSStoryStatus', FieldValue: '' },
          { FieldName: 'MOSStoryStatusMOS', FieldValue: '' },
          {
            FieldName: 'MOSStoryStatusTime',
            FieldValue: '1800-01-01T00:00:00Z',
          },
          { FieldName: 'ModBy', FieldValue: 'O.ROACH' },
          { FieldName: 'RowModBy', FieldValue: 'zns.precis1.nassau.mos' },
          { FieldName: 'DoNotArchive', FieldValue: true },
          { FieldName: 'Printed', FieldValue: '2023-12-28T18:13:37Z' },
          { FieldName: 'Database', FieldValue: 'svrscala-backup' },
          {
            FieldName: 'Path',
            FieldValue: 'P_NASNEWS\\W\\R_F9114187-6CF7-4929-BC673F4A2B79E2C5',
          },
          { FieldName: 'Title', FieldValue: 'Z INTRO 2PM UPDATE-SOT' },
          { FieldName: 'OutputType', FieldValue: 0 },
          { FieldName: 'PageNum', FieldValue: 'A1' },
          { FieldName: 'UserCanWritePermissions', FieldValue: true },
          { FieldName: 'CumeTime', FieldValue: 0 },
          { FieldName: 'ObjectPlaceholderCreate', FieldValue: '' },
          { FieldName: 'Reporter', FieldValue: '' },
          { FieldName: 'Float', FieldValue: false },
          { FieldName: 'Break', FieldValue: false },
          { FieldName: 'Estimated', FieldValue: 0 },
          { FieldName: 'Actual', FieldValue: 0 },
          { FieldName: 'BackTime', FieldValue: '1800-01-01T00:00:00' },
        ],
        ListData: {
          ENPSDatabase: 'svrscala-backup',
          Path: 'P_NASNEWS\\W\\R_F9114187-6CF7-4929-BC673F4A2B79E2C5',
          Guid: '6141794A-A342-4D6A-A26C90A0639CA9F7',
          ContainerTitle: '2PM Update',
          Title: 'Z INTRO 2PM UPDATE-SOT',
          Type: 3,
          Priority: 0,
          Approved: false,
          OutputType: 0,
          Creator: 'J.SAUNDERS',
          ModBy: 'O.ROACH',
          MosObjId: '',
          MosControl: false,
          ModTime: '2022-10-12T19:11:32Z',
          Expires: '2022-11-11T20:11:32Z',
          Owner: 'J.SAUNDERS',
          BeginText: '\r\n\r\n',
          FileStorageVersion: 0,
        },
        ObjectLinks: { LinkedRecords: { $id: '1', $values: [] } },
        SocialMediaLinks: [],
        ObjectTags: { Tags: [] },
        ChatData: [],
        IsSearchReturnedResult: false,
      },
      Float: false,
      Break: false,
      HasYellowTimingBar: false,
      CBreak: false,
      NotForBroadcast: false,
    },
    {
      CollectionsCollection: null,
      ScriptOrder: 2,
      PageNum: 'A2',
      FrontTime: '2023-12-28T19:00:00Z',
      FrontTimeFormatted: '07:00:00 PM',
      BackTime: '2023-12-28T19:04:14Z',
      BackTimeFormatted: '07:04:14 PM',
      FrontOverUnder: '-10675199.00:00:00',
      BackOverUnder: '-10675199.00:00:00',
      CumeTime: '00:00:23',
      CumeTimeFormatted: '0:23',
      BackCumeTime: '00:00:46',
      BackCumeTimeFormatted: '0:46',
      IsTimingBarSelected: false,
      IsRowFlashing: false,
      IsFrozen: false,
      RecordPointer: {
        ReadTime: 23,
        Actual: null,
        Estimated: '00:00:00',
        HardHitFront: '1800-01-01T00:00:00',
        HardHitBack: '1800-01-01T00:00:00',
        ActualTimeString: { Key: 'ReadTime', Value: '0:23' },
        DefaultLayout: null,
        Loading: false,
        ObjectProperties: [
          { FieldName: 'TextCommands', FieldValue: {} },
          {
            FieldName: 'Text',
            FieldValue:
              '<html xmlns="http://www.w3.org/1999/xhtml">\r\n<head><title></title></head>\r\n<body><span>THIS&#160;IS&#160;THE&#160;&#160;ZNS&#160;NEWS&#160;HEADLINES&#160;AT&#160;THE&#160;HOUR..GOOD&#160;AFTERNOON&#160;EVERYONE&#160;I\'M&#160;LEDAUNNE&#160;DAVIS.HERE\'S&#160;SOME&#160;OF&#160;THE&#160;STORIES&#160;WE\'RE&#160;WORKING&#160;ON.<br /><br />\r\nSOME&#160;NEW&#160;CABINET&#160;APPONTMENTS&#160;WILL&#160;TAKE&#160;EFFECT&#160;ON&#160;JANUARY&#160;2ND,&#160;2024.</span><span style="color:#000000;">THE&#160;HON&#160;MYLES&#160;LARODA&#160;HAS&#160;BEN&#160;&#160;PROMOTED&#160;TO</span><span style="font-weight:bold;color:#000000;">&#160;</span><span style="color:#000000;">MINISTER&#160;OF&#160;SOCIAL&#160;SERVICES,&#160;INFORMATION&#160;AND&#160;BROADCASTING;&#160;THE&#160;HON&#160;LEON&#160;LUNDY&#160;IS&#160;NOW&#160;&#160;MINISTER&#160;OF&#160;STATE&#160;IN&#160;THE&#160;OFFICE&#160;OF&#160;THE&#160;PRIME&#160;MINISTER&#160;AND&#160;&#160;KINGSLEY&#160;SMITH&#160;WILL&#160;NOW&#160;SERVE&#160;AS&#160;PARLIAMENTARY&#160;SECRETARY&#160;IN&#160;THE&#160;MINISTRY&#160;FOR&#160;GRAND&#160;BAHAMA.<br />\r\n---------------------------------<br /><br /></span></body></html>',
          },
          { FieldName: 'VPContainsRTL', FieldValue: false },
          { FieldName: 'Owner', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'Creator', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'ModBy', FieldValue: 'L.DAVIS' },
          { FieldName: 'AnchorTime', FieldValue: '2019-07-19T16:08:23Z' },
          { FieldName: 'Expires', FieldValue: '2024-01-27T18:09:20Z' },
          { FieldName: 'ModTime', FieldValue: '2023-12-28T18:09:20Z' },
          { FieldName: 'Type', FieldValue: 3 },
          { FieldName: 'SourceModBy', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'SourceModTime', FieldValue: '2019-07-19T16:07:06Z' },
          {
            FieldName: 'GUID',
            FieldValue: 'FBCD6414-5CB9-4264-97DB5569454D03C6',
          },
          { FieldName: 'pubApproved', FieldValue: false },
          { FieldName: 'ScriptSubType', FieldValue: 'Broadcast' },
          { FieldName: 'Priority', FieldValue: 0 },
          { FieldName: 'Approved', FieldValue: false },
          { FieldName: 'Version', FieldValue: 2 },
          { FieldName: 'Status', FieldValue: '3' },
          { FieldName: 'WriteCount', FieldValue: 8 },
          { FieldName: 'RowModTime', FieldValue: '2023-12-28T18:13:37Z' },
          { FieldName: 'RowModBy', FieldValue: 'L.DAVIS' },
          { FieldName: 'ReadTime', FieldValue: 23 },
          { FieldName: 'MediaTime', FieldValue: '00:00:00' },
          { FieldName: 'TextTime', FieldValue: '00:00:23' },
          { FieldName: 'SourceReadTime', FieldValue: 0 },
          { FieldName: 'SourceMediaTime', FieldValue: '00:00:00' },
          { FieldName: 'SourceTextTime', FieldValue: '00:00:00' },
          {
            FieldName: 'OutCue',
            FieldValue: 'GRAND BAHAMA. ---------------------------------',
          },
          { FieldName: 'LastKbdUsed', FieldValue: '67699721' },
          { FieldName: 'Printed', FieldValue: '2023-12-28T18:13:37Z' },
          { FieldName: 'Database', FieldValue: 'svrscala-backup' },
          {
            FieldName: 'Path',
            FieldValue: 'P_NASNEWS\\W\\R_F9114187-6CF7-4929-BC673F4A2B79E2C5',
          },
          { FieldName: 'Title', FieldValue: 'CABINET APPOINTMENTS- SCRIPTS' },
          { FieldName: 'OutputType', FieldValue: 0 },
          { FieldName: 'PageNum', FieldValue: 'A2' },
          { FieldName: 'UserCanWritePermissions', FieldValue: true },
          { FieldName: 'CumeTime', FieldValue: 0 },
          { FieldName: 'DoNotArchive', FieldValue: false },
          { FieldName: 'MOSObjSlugs', FieldValue: '' },
          { FieldName: 'ObjectPlaceholderCreate', FieldValue: '' },
          { FieldName: 'MOSChannels', FieldValue: '' },
          { FieldName: 'Reporter', FieldValue: '' },
          { FieldName: 'MOSStatus', FieldValue: '' },
          { FieldName: 'Float', FieldValue: false },
          { FieldName: 'Break', FieldValue: false },
          { FieldName: 'Estimated', FieldValue: 0 },
          { FieldName: 'Actual', FieldValue: 0 },
          { FieldName: 'BackTime', FieldValue: '1800-01-01T00:00:00' },
        ],
        ListData: {
          ENPSDatabase: 'svrscala-backup',
          Path: 'P_NASNEWS\\W\\R_F9114187-6CF7-4929-BC673F4A2B79E2C5',
          Guid: 'FBCD6414-5CB9-4264-97DB5569454D03C6',
          ContainerTitle: '2PM Update',
          Title: 'CABINET APPOINTMENTS- SCRIPTS',
          Type: 3,
          Priority: 0,
          Approved: false,
          OutputType: 0,
          Creator: 'J.SAUNDERS',
          ModBy: 'L.DAVIS',
          MosObjId: '',
          MosControl: false,
          ModTime: '2023-12-28T18:09:20Z',
          Expires: '2024-01-27T18:09:20Z',
          Owner: 'J.SAUNDERS',
          BeginText:
            "THIS IS THE  ZNS NEWS HEADLINES AT THE HOUR..GOOD AFTERNOON EVERYONE I'M LEDAUNNE DAVIS.HERE'S SOME OF THE STORIES WE'RE WORKING ON.\r\n\r\nSOME NEW CABINET APPONTMENTS WILL TAKE EFFECT ON JANUARY 2ND, 2024.THE HON MYLES LARODA HAS BEN  PROMOTED TO MINISTER OF SOCIAL SERVICES, INFORMATION AND BROADCASTING; THE HON LEON LUNDY IS NOW  MINISTER OF STATE IN THE OFFICE OF THE PRIME MINISTER AND  KINGSLEY SMITH WILL NOW SERVE AS PARLIAMENTARY SECRETARY IN THE MINISTRY FOR GRAND BAHAMA.\r\n---------------------------------\r\n\r\n",
          FileStorageVersion: 0,
        },
        ObjectLinks: { LinkedRecords: { $id: '2', $values: [] } },
        SocialMediaLinks: [],
        ObjectTags: { Tags: [] },
        ChatData: [],
        IsSearchReturnedResult: false,
      },
      Float: false,
      Break: false,
      HasYellowTimingBar: false,
      CBreak: false,
      NotForBroadcast: false,
    },
    {
      CollectionsCollection: null,
      ScriptOrder: 3,
      PageNum: 'A3',
      FrontTime: '2023-12-28T19:00:23Z',
      FrontTimeFormatted: '07:00:23 PM',
      BackTime: '2023-12-28T19:04:37Z',
      BackTimeFormatted: '07:04:37 PM',
      FrontOverUnder: '-10675199.00:00:00',
      BackOverUnder: '-10675199.00:00:00',
      CumeTime: '00:00:32',
      CumeTimeFormatted: '0:32',
      BackCumeTime: '00:00:23',
      BackCumeTimeFormatted: '0:23',
      IsTimingBarSelected: false,
      IsRowFlashing: false,
      IsFrozen: false,
      RecordPointer: {
        ReadTime: 9,
        Actual: null,
        Estimated: '00:00:00',
        HardHitFront: '1800-01-01T00:00:00',
        HardHitBack: '1800-01-01T00:00:00',
        ActualTimeString: { Key: 'ReadTime', Value: '0:09' },
        DefaultLayout: null,
        Loading: false,
        ObjectProperties: [
          { FieldName: 'TextCommands', FieldValue: {} },
          {
            FieldName: 'Text',
            FieldValue:
              '<html xmlns="http://www.w3.org/1999/xhtml">\r\n<head><title></title></head>\r\n<body><span>SOME&#160;GOOD&#160;NEWS&#160;FOR&#160;THE&#160;COUNTRY\'S&#160;ECONOMY&#160;IN&#160;2024...ITS&#160;PROJECTED&#160;BY&#160;THE&#160;INTERNATIONAL&#160;MONETARY&#160;FUND&#160;THAT&#160;THE&#160;DOMESTIC&#160;ECONOMY&#160;WILL&#160;GROW&#160;BY&#160;ABOUT&#160;2.3&#160;PERCENT,&#160;UP&#160;FROM&#160;THE&#160;PREVIOUS&#160;PROJECTION&#160;OF&#160;1.8&#160;PERCENT..</span></body></html>',
          },
          { FieldName: 'VPContainsRTL', FieldValue: false },
          { FieldName: 'Owner', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'Creator', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'ModBy', FieldValue: 'L.DAVIS' },
          { FieldName: 'AnchorTime', FieldValue: '2019-07-19T16:08:23Z' },
          { FieldName: 'Expires', FieldValue: '2024-01-27T18:12:25Z' },
          { FieldName: 'ModTime', FieldValue: '2023-12-28T18:12:25Z' },
          { FieldName: 'Type', FieldValue: 3 },
          { FieldName: 'SourceModBy', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'SourceModTime', FieldValue: '2019-07-19T16:07:16Z' },
          {
            FieldName: 'GUID',
            FieldValue: '913436FE-100E-4883-AAE9244055AE3876',
          },
          { FieldName: 'pubApproved', FieldValue: false },
          { FieldName: 'ScriptSubType', FieldValue: 'Broadcast' },
          { FieldName: 'Priority', FieldValue: 0 },
          { FieldName: 'Approved', FieldValue: false },
          { FieldName: 'Version', FieldValue: 1 },
          { FieldName: 'Status', FieldValue: '3' },
          { FieldName: 'WriteCount', FieldValue: 7 },
          { FieldName: 'RowModTime', FieldValue: '2023-12-28T18:13:37Z' },
          { FieldName: 'RowModBy', FieldValue: 'L.DAVIS' },
          { FieldName: 'ReadTime', FieldValue: 9 },
          { FieldName: 'MediaTime', FieldValue: '00:00:00' },
          { FieldName: 'TextTime', FieldValue: '00:00:09' },
          { FieldName: 'SourceReadTime', FieldValue: 0 },
          { FieldName: 'SourceMediaTime', FieldValue: '00:00:00' },
          { FieldName: 'SourceTextTime', FieldValue: '00:00:00' },
          {
            FieldName: 'OutCue',
            FieldValue: 'UP FROM THE PREVIOUS PROJECTION OF 1.8 PERCENT..',
          },
          { FieldName: 'LastKbdUsed', FieldValue: '67699721' },
          { FieldName: 'Printed', FieldValue: '2023-12-28T18:13:37Z' },
          { FieldName: 'Database', FieldValue: 'svrscala-backup' },
          {
            FieldName: 'Path',
            FieldValue: 'P_NASNEWS\\W\\R_F9114187-6CF7-4929-BC673F4A2B79E2C5',
          },
          { FieldName: 'Title', FieldValue: 'IMF ON ECONOMY-SCRIPT' },
          { FieldName: 'OutputType', FieldValue: 0 },
          { FieldName: 'PageNum', FieldValue: 'A3' },
          { FieldName: 'UserCanWritePermissions', FieldValue: true },
          { FieldName: 'CumeTime', FieldValue: 0 },
          { FieldName: 'DoNotArchive', FieldValue: false },
          { FieldName: 'MOSObjSlugs', FieldValue: '' },
          { FieldName: 'ObjectPlaceholderCreate', FieldValue: '' },
          { FieldName: 'MOSChannels', FieldValue: '' },
          { FieldName: 'Reporter', FieldValue: '' },
          { FieldName: 'MOSStatus', FieldValue: '' },
          { FieldName: 'Float', FieldValue: false },
          { FieldName: 'Break', FieldValue: false },
          { FieldName: 'Estimated', FieldValue: 0 },
          { FieldName: 'Actual', FieldValue: 0 },
          { FieldName: 'BackTime', FieldValue: '1800-01-01T00:00:00' },
        ],
        ListData: {
          ENPSDatabase: 'svrscala-backup',
          Path: 'P_NASNEWS\\W\\R_F9114187-6CF7-4929-BC673F4A2B79E2C5',
          Guid: '913436FE-100E-4883-AAE9244055AE3876',
          ContainerTitle: '2PM Update',
          Title: 'IMF ON ECONOMY-SCRIPT',
          Type: 3,
          Priority: 0,
          Approved: false,
          OutputType: 0,
          Creator: 'J.SAUNDERS',
          ModBy: 'L.DAVIS',
          MosObjId: '',
          MosControl: false,
          ModTime: '2023-12-28T18:12:25Z',
          Expires: '2024-01-27T18:12:25Z',
          Owner: 'J.SAUNDERS',
          BeginText:
            "SOME GOOD NEWS FOR THE COUNTRY'S ECONOMY IN 2024...ITS PROJECTED BY THE INTERNATIONAL MONETARY FUND THAT THE DOMESTIC ECONOMY WILL GROW BY ABOUT 2.3 PERCENT, UP FROM THE PREVIOUS PROJECTION OF 1.8 PERCENT..",
          FileStorageVersion: 0,
        },
        ObjectLinks: { LinkedRecords: { $id: '3', $values: [] } },
        SocialMediaLinks: [],
        ObjectTags: { Tags: [] },
        ChatData: [],
        IsSearchReturnedResult: false,
      },
      Float: false,
      Break: false,
      HasYellowTimingBar: false,
      CBreak: false,
      NotForBroadcast: false,
    },
    {
      CollectionsCollection: null,
      ScriptOrder: 4,
      PageNum: 'A4',
      FrontTime: '2023-12-28T19:00:32Z',
      FrontTimeFormatted: '07:00:32 PM',
      BackTime: '2023-12-28T19:04:46Z',
      BackTimeFormatted: '07:04:46 PM',
      FrontOverUnder: '-10675199.00:00:00',
      BackOverUnder: '-10675199.00:00:00',
      CumeTime: '00:00:46',
      CumeTimeFormatted: '0:46',
      BackCumeTime: '00:00:14',
      BackCumeTimeFormatted: '0:14',
      IsTimingBarSelected: false,
      IsRowFlashing: false,
      IsFrozen: false,
      RecordPointer: {
        ReadTime: 14,
        Actual: null,
        Estimated: '00:00:00',
        HardHitFront: '1800-01-01T00:00:00',
        HardHitBack: '1800-01-01T00:00:00',
        ActualTimeString: { Key: 'ReadTime', Value: '0:14' },
        DefaultLayout: null,
        Loading: false,
        ObjectProperties: [
          { FieldName: 'TextCommands', FieldValue: {} },
          {
            FieldName: 'Text',
            FieldValue:
              '<html xmlns="http://www.w3.org/1999/xhtml">\r\n<head><title></title></head>\r\n<body><span>AND&#160;A&#160;17&#160;YEAR&#160;OLD&#160;IS&#160;NURSING&#160;WOUNDS&#160;IN&#160;HOSPITAL&#160;AFTER&#160;ATTEMPTS&#160;TO&#160;EXTINGUISH&#160;A&#160;&#160;FIRE&#160;WORK&#160;SHELL&#160;FAILED..FIRE&#160;OFFICIALS&#160;SAY&#160;THE&#160;INCIDENT&#160;HAPPENED&#160;AROUND&#160;8:30&#160;ON&#160;WEDNESDAY&#160;NIGHT&#160;AT&#160;A&#160;HOME&#160;ON&#160;ST&#160;THOMAS&#160;ROAD.&#160;INVESTIGATIONS&#160;CONTINUE.<br /><br />\r\nAND&#160;THATS&#160;STORIES&#160;MAKING&#160;NEWS&#160;AT&#160;THIS&#160;HOUR..&#160;ONCE&#160;AGAIN,&#160;IM&#160;LEDAUNNE&#160;DAVIS..&#160;GOOD&#160;AFTERNOON.</span></body></html>',
          },
          { FieldName: 'VPContainsRTL', FieldValue: false },
          { FieldName: 'Owner', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'Creator', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'ModBy', FieldValue: 'L.DAVIS' },
          { FieldName: 'AnchorTime', FieldValue: '2019-07-19T16:08:23Z' },
          { FieldName: 'Expires', FieldValue: '2024-01-27T18:13:30Z' },
          { FieldName: 'ModTime', FieldValue: '2023-12-28T18:13:30Z' },
          { FieldName: 'Type', FieldValue: 3 },
          { FieldName: 'SourceModBy', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'SourceModTime', FieldValue: '2019-07-19T16:07:10Z' },
          {
            FieldName: 'GUID',
            FieldValue: '12375D2D-08AB-42E6-A2466AB07E0E7398',
          },
          { FieldName: 'pubApproved', FieldValue: false },
          { FieldName: 'ScriptSubType', FieldValue: 'Broadcast' },
          { FieldName: 'Priority', FieldValue: 0 },
          { FieldName: 'Approved', FieldValue: false },
          { FieldName: 'Version', FieldValue: 3 },
          { FieldName: 'Status', FieldValue: '3' },
          { FieldName: 'WriteCount', FieldValue: 10 },
          { FieldName: 'RowModTime', FieldValue: '2023-12-28T18:13:37Z' },
          { FieldName: 'RowModBy', FieldValue: 'L.DAVIS' },
          { FieldName: 'ReadTime', FieldValue: 14 },
          { FieldName: 'MediaTime', FieldValue: '00:00:00' },
          { FieldName: 'TextTime', FieldValue: '00:00:14' },
          { FieldName: 'SourceReadTime', FieldValue: 0 },
          { FieldName: 'SourceMediaTime', FieldValue: '00:00:00' },
          { FieldName: 'SourceTextTime', FieldValue: '00:00:00' },
          {
            FieldName: 'OutCue',
            FieldValue: 'ONCE AGAIN, IM LEDAUNNE DAVIS.. GOOD AFTERNOON.',
          },
          { FieldName: 'LastKbdUsed', FieldValue: '67699721' },
          { FieldName: 'Printed', FieldValue: '2023-12-28T18:13:37Z' },
          { FieldName: 'Database', FieldValue: 'svrscala-backup' },
          {
            FieldName: 'Path',
            FieldValue: 'P_NASNEWS\\W\\R_F9114187-6CF7-4929-BC673F4A2B79E2C5',
          },
          { FieldName: 'Title', FieldValue: 'FIRE VICTIM INJURED-SCRIPT' },
          { FieldName: 'OutputType', FieldValue: 0 },
          { FieldName: 'PageNum', FieldValue: 'A4' },
          { FieldName: 'UserCanWritePermissions', FieldValue: true },
          { FieldName: 'CumeTime', FieldValue: 0 },
          { FieldName: 'DoNotArchive', FieldValue: false },
          { FieldName: 'MOSObjSlugs', FieldValue: '' },
          { FieldName: 'ObjectPlaceholderCreate', FieldValue: '' },
          { FieldName: 'MOSChannels', FieldValue: '' },
          { FieldName: 'Reporter', FieldValue: '' },
          { FieldName: 'MOSStatus', FieldValue: '' },
          { FieldName: 'Float', FieldValue: false },
          { FieldName: 'Break', FieldValue: false },
          { FieldName: 'Estimated', FieldValue: 0 },
          { FieldName: 'Actual', FieldValue: 0 },
          { FieldName: 'BackTime', FieldValue: '1800-01-01T00:00:00' },
        ],
        ListData: {
          ENPSDatabase: 'svrscala-backup',
          Path: 'P_NASNEWS\\W\\R_F9114187-6CF7-4929-BC673F4A2B79E2C5',
          Guid: '12375D2D-08AB-42E6-A2466AB07E0E7398',
          ContainerTitle: '2PM Update',
          Title: 'FIRE VICTIM INJURED-SCRIPT',
          Type: 3,
          Priority: 0,
          Approved: false,
          OutputType: 0,
          Creator: 'J.SAUNDERS',
          ModBy: 'L.DAVIS',
          MosObjId: '',
          MosControl: false,
          ModTime: '2023-12-28T18:13:30Z',
          Expires: '2024-01-27T18:13:30Z',
          Owner: 'J.SAUNDERS',
          BeginText:
            'AND A 17 YEAR OLD IS NURSING WOUNDS IN HOSPITAL AFTER ATTEMPTS TO EXTINGUISH A  FIRE WORK SHELL FAILED..FIRE OFFICIALS SAY THE INCIDENT HAPPENED AROUND 8:30 ON WEDNESDAY NIGHT AT A HOME ON ST THOMAS ROAD. INVESTIGATIONS CONTINUE.\r\n\r\nAND THATS STORIES MAKING NEWS AT THIS HOUR.. ONCE AGAIN, IM LEDAUNNE DAVIS.. GOOD AFTERNOON.',
          FileStorageVersion: 0,
        },
        ObjectLinks: { LinkedRecords: { $id: '4', $values: [] } },
        SocialMediaLinks: [],
        ObjectTags: { Tags: [] },
        ChatData: [],
        IsSearchReturnedResult: false,
      },
      Float: false,
      Break: false,
      HasYellowTimingBar: false,
      CBreak: false,
      NotForBroadcast: false,
    },
    {
      CollectionsCollection: null,
      ScriptOrder: 5,
      PageNum: 'A5',
      FrontTime: '2023-12-28T19:00:46Z',
      FrontTimeFormatted: '07:00:46 PM',
      BackTime: '2023-12-28T19:05:00Z',
      BackTimeFormatted: '07:05:00 PM',
      FrontOverUnder: '-10675199.00:00:00',
      BackOverUnder: '-10675199.00:00:00',
      CumeTime: '00:00:46',
      CumeTimeFormatted: '0:46',
      BackCumeTime: '00:00:00',
      BackCumeTimeFormatted: '0:00',
      IsTimingBarSelected: false,
      IsRowFlashing: false,
      IsFrozen: false,
      RecordPointer: {
        ReadTime: 0,
        Actual: null,
        Estimated: '00:00:00',
        HardHitFront: '1800-01-01T00:00:00',
        HardHitBack: '1800-01-01T00:00:00',
        ActualTimeString: { Key: 'ReadTime', Value: '0:00' },
        DefaultLayout: null,
        Loading: false,
        ObjectProperties: [
          {
            FieldName: 'TextCommands',
            FieldValue: {
              '4d7aed82-c818-4916-ac26-42559ee98c6e':
                '[<mos><itemID>2</itemID><itemSlug>Z EXTRO 2PM UPDATE-SOT</itemSlug><objID>54dd9610-0cf0-49eb-8c86-a50d2bafb067</objID><mosID>zns.precis1.nassau.mos</mosID><mosAbstract>Z EXTRO 2PM UPDATE-SOT_NEWSEDIT-C_Admin_20221007_125935.mxf</mosAbstract><objDur>687</objDur><objTB>60</objTB><objSlug>Z EXTRO 2PM UPDATE-SOT_NEWSEDIT-C_Admin_20221007_125935.mxf</objSlug><objType>VIDEO</objType><itemChannel>A</itemChannel><itemEdStart>0</itemEdStart><itemEdDur>0</itemEdDur><objAir>NOT READY</objAir><objPaths><objPath>https://ZNS-BCCS01.znsbahamas.com:10456/broadcast/54dd9610-0cf0-49eb-8c86-a50d2bafb067.mxf</objPath><objProxyPath techDescription="Proxy">https://ZNS-BCCS01.znsbahamas.com:10456/proxy/54dd9610-0cf0-49eb-8c86-a50d2bafb067Proxy.mp4</objProxyPath><objProxyPath techDescription="JPG">https://ZNS-BCCS01.znsbahamas.com:10456/still/54dd9610-0cf0-49eb-8c86-a50d2bafb067.jpg</objProxyPath></objPaths><mosExternalMetadata><mosScope>STORY</mosScope><mosSchema>http://bitcentral.com/schemas/mos/2.0</mosSchema><mosPayload/></mosExternalMetadata></mos>]',
            },
          },
          {
            FieldName: 'Text',
            FieldValue:
              '<html xmlns="http://www.w3.org/1999/xhtml">\r\n<head><title></title></head>\r\n<body><br /><span class="MOS-zns.precis1.nassau.mos" id="4d7aed82-c818-4916-ac26-42559ee98c6e"></span><br /></body></html>',
          },
          { FieldName: 'VPContainsRTL', FieldValue: false },
          { FieldName: 'Type', FieldValue: 3 },
          { FieldName: 'Owner', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'Creator', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'AnchorTime', FieldValue: '2022-10-06T15:21:38Z' },
          { FieldName: 'Approved', FieldValue: false },
          { FieldName: 'pubApproved', FieldValue: false },
          {
            FieldName: 'GUID',
            FieldValue: 'A240D06D-7D06-44BC-8A75210AB40155C6',
          },
          { FieldName: 'Expires', FieldValue: '2022-11-11T20:11:36Z' },
          { FieldName: 'ModTime', FieldValue: '2022-10-12T19:11:36Z' },
          { FieldName: 'Priority', FieldValue: 0 },
          { FieldName: 'Version', FieldValue: 2 },
          { FieldName: 'Status', FieldValue: '3' },
          { FieldName: 'WriteCount', FieldValue: 20 },
          { FieldName: 'RowModTime', FieldValue: '2023-12-29T12:01:00Z' },
          { FieldName: 'ScriptSubType', FieldValue: 'Broadcast' },
          { FieldName: 'LastMOSItemID', FieldValue: '2' },
          { FieldName: 'ReadTime', FieldValue: 0 },
          { FieldName: 'MediaTime', FieldValue: '00:00:00' },
          { FieldName: 'TextTime', FieldValue: '00:00:00' },
          { FieldName: 'SourceReadTime', FieldValue: 0 },
          { FieldName: 'SourceMediaTime', FieldValue: '00:00:00' },
          { FieldName: 'SourceTextTime', FieldValue: '00:00:00' },
          { FieldName: 'MOSIDs', FieldValue: 'zns.precis1.nassau.mos' },
          {
            FieldName: 'MOSObjIDs',
            FieldValue: '54dd9610-0cf0-49eb-8c86-a50d2bafb067',
          },
          { FieldName: 'MOSSlugs', FieldValue: 'Z EXTRO 2PM UPDATE-SOT' },
          { FieldName: 'MOSItemDurations', FieldValue: '0:11' },
          {
            FieldName: 'MOSAbstracts',
            FieldValue:
              'Z EXTRO 2PM UPDATE-SOT_NEWSEDIT-C_Admin_20221007_125935.mxf',
          },
          {
            FieldName: 'MOSObjSlugs',
            FieldValue:
              'Z EXTRO 2PM UPDATE-SOT_NEWSEDIT-C_Admin_20221007_125935.mxf',
          },
          { FieldName: 'MOSItemIDs', FieldValue: '2' },
          { FieldName: 'MOSStatus', FieldValue: 'Linked' },
          { FieldName: 'MOSTimes', FieldValue: '7:01:00 AM' },
          { FieldName: 'MOSChannels', FieldValue: ['A'] },
          { FieldName: 'MOSItemEdDurations', FieldValue: '0:00' },
          {
            FieldName: 'MOSItemPaths',
            FieldValue:
              '<objPath>https://ZNS-BCCS01.znsbahamas.com:10456/broadcast/54dd9610-0cf0-49eb-8c86-a50d2bafb067.mxf</objPath><objProxyPath techDescription="Proxy">https://ZNS-BCCS01.znsbahamas.com:10456/proxy/54dd9610-0cf0-49eb-8c86-a50d2bafb067Proxy.mp4</objProxyPath><objProxyPath techDescription="JPG">https://ZNS-BCCS01.znsbahamas.com:10456/still/54dd9610-0cf0-49eb-8c86-a50d2bafb067.jpg</objProxyPath>',
          },
          {
            FieldName: 'MOSItemPathsBBL',
            FieldValue:
              '<objPath>https://ZNS-BCCS01.znsbahamas.com:10456/broadcast/54dd9610-0cf0-49eb-8c86-a50d2bafb067.mxf</objPath><objProxyPath techDescription="Proxy">https://ZNS-BCCS01.znsbahamas.com:10456/proxy/54dd9610-0cf0-49eb-8c86-a50d2bafb067Proxy.mp4</objProxyPath><objProxyPath techDescription="JPG">https://ZNS-BCCS01.znsbahamas.com:10456/still/54dd9610-0cf0-49eb-8c86-a50d2bafb067.jpg</objProxyPath>',
          },
          { FieldName: 'MOSStoryStatus', FieldValue: '' },
          { FieldName: 'MOSStoryStatusMOS', FieldValue: '' },
          {
            FieldName: 'MOSStoryStatusTime',
            FieldValue: '1800-01-01T00:00:00Z',
          },
          { FieldName: 'ModBy', FieldValue: 'O.ROACH' },
          { FieldName: 'RowModBy', FieldValue: 'zns.precis1.nassau.mos' },
          { FieldName: 'DoNotArchive', FieldValue: true },
          { FieldName: 'Printed', FieldValue: '2023-12-28T18:13:37Z' },
          { FieldName: 'Database', FieldValue: 'svrscala-backup' },
          {
            FieldName: 'Path',
            FieldValue: 'P_NASNEWS\\W\\R_F9114187-6CF7-4929-BC673F4A2B79E2C5',
          },
          { FieldName: 'Title', FieldValue: 'Z EXTRO 2PM UPDATE-SOT' },
          { FieldName: 'OutputType', FieldValue: 0 },
          { FieldName: 'PageNum', FieldValue: 'A5' },
          { FieldName: 'UserCanWritePermissions', FieldValue: true },
          { FieldName: 'CumeTime', FieldValue: 0 },
          { FieldName: 'ObjectPlaceholderCreate', FieldValue: '' },
          { FieldName: 'Reporter', FieldValue: '' },
          { FieldName: 'Float', FieldValue: false },
          { FieldName: 'Break', FieldValue: false },
          { FieldName: 'Estimated', FieldValue: 0 },
          { FieldName: 'Actual', FieldValue: 0 },
          { FieldName: 'BackTime', FieldValue: '1800-01-01T00:00:00' },
        ],
        ListData: {
          ENPSDatabase: 'svrscala-backup',
          Path: 'P_NASNEWS\\W\\R_F9114187-6CF7-4929-BC673F4A2B79E2C5',
          Guid: 'A240D06D-7D06-44BC-8A75210AB40155C6',
          ContainerTitle: '2PM Update',
          Title: 'Z EXTRO 2PM UPDATE-SOT',
          Type: 3,
          Priority: 0,
          Approved: false,
          OutputType: 0,
          Creator: 'J.SAUNDERS',
          ModBy: 'O.ROACH',
          MosObjId: '',
          MosControl: false,
          ModTime: '2022-10-12T19:11:36Z',
          Expires: '2022-11-11T20:11:36Z',
          Owner: 'J.SAUNDERS',
          BeginText: '\r\n\r\n',
          FileStorageVersion: 0,
        },
        ObjectLinks: { LinkedRecords: { $id: '5', $values: [] } },
        SocialMediaLinks: [],
        ObjectTags: { Tags: [] },
        ChatData: [],
        IsSearchReturnedResult: false,
      },
      Float: false,
      Break: false,
      HasYellowTimingBar: false,
      CBreak: false,
      NotForBroadcast: false,
    },
    {
      CollectionsCollection: null,
      ScriptOrder: 6,
      PageNum: 'A6',
      FrontTime: '2023-12-28T19:00:46Z',
      FrontTimeFormatted: '07:00:46 PM',
      BackTime: '2023-12-28T19:05:00Z',
      BackTimeFormatted: '07:05:00 PM',
      FrontOverUnder: '-10675199.00:00:00',
      BackOverUnder: '-10675199.00:00:00',
      CumeTime: '00:00:46',
      CumeTimeFormatted: '0:46',
      BackCumeTime: '00:00:00',
      BackCumeTimeFormatted: '0:00',
      IsTimingBarSelected: false,
      IsRowFlashing: false,
      IsFrozen: false,
      RecordPointer: {
        ReadTime: 0,
        Actual: null,
        Estimated: '00:00:00',
        HardHitFront: '1800-01-01T00:00:00',
        HardHitBack: '1800-01-01T00:00:00',
        ActualTimeString: { Key: 'ReadTime', Value: '0:00' },
        DefaultLayout: null,
        Loading: false,
        ObjectProperties: [
          { FieldName: 'TextCommands', FieldValue: {} },
          { FieldName: 'Text', FieldValue: '' },
          { FieldName: 'VPContainsRTL', FieldValue: false },
          { FieldName: 'Owner', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'Creator', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'ModBy', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'AnchorTime', FieldValue: '2019-07-19T16:08:23Z' },
          { FieldName: 'Expires', FieldValue: '2019-08-18T16:08:23Z' },
          { FieldName: 'ModTime', FieldValue: '2019-07-19T16:08:23Z' },
          { FieldName: 'Type', FieldValue: 3 },
          { FieldName: 'SourceModBy', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'SourceModTime', FieldValue: '2019-07-19T16:07:14Z' },
          {
            FieldName: 'GUID',
            FieldValue: 'B0CDBF90-32A4-4A59-884CB51C024E69D7',
          },
          { FieldName: 'pubApproved', FieldValue: false },
          { FieldName: 'ScriptSubType', FieldValue: 'Broadcast' },
          { FieldName: 'Priority', FieldValue: 0 },
          { FieldName: 'Approved', FieldValue: false },
          { FieldName: 'Version', FieldValue: 0 },
          { FieldName: 'Status', FieldValue: '2' },
          { FieldName: 'WriteCount', FieldValue: 4 },
          { FieldName: 'RowModTime', FieldValue: '2023-12-28T12:00:01Z' },
          { FieldName: 'RowModBy', FieldValue: 'AutoCreate' },
          { FieldName: 'Database', FieldValue: 'svrscala-backup' },
          {
            FieldName: 'Path',
            FieldValue: 'P_NASNEWS\\W\\R_F9114187-6CF7-4929-BC673F4A2B79E2C5',
          },
          { FieldName: 'Title', FieldValue: 'New Row 3 Jason Saunders' },
          { FieldName: 'OutputType', FieldValue: 0 },
          { FieldName: 'PageNum', FieldValue: 'A6' },
          { FieldName: 'UserCanWritePermissions', FieldValue: true },
          { FieldName: 'CumeTime', FieldValue: 0 },
          { FieldName: 'DoNotArchive', FieldValue: false },
          { FieldName: 'MOSObjSlugs', FieldValue: '' },
          { FieldName: 'ObjectPlaceholderCreate', FieldValue: '' },
          { FieldName: 'MOSChannels', FieldValue: '' },
          { FieldName: 'Reporter', FieldValue: '' },
          { FieldName: 'MOSStatus', FieldValue: '' },
          { FieldName: 'Float', FieldValue: false },
          { FieldName: 'Break', FieldValue: false },
          { FieldName: 'Estimated', FieldValue: 0 },
          { FieldName: 'Actual', FieldValue: 0 },
          { FieldName: 'ReadTime', FieldValue: 0 },
          { FieldName: 'BackTime', FieldValue: '1800-01-01T00:00:00' },
        ],
        ListData: {
          ENPSDatabase: 'svrscala-backup',
          Path: 'P_NASNEWS\\W\\R_F9114187-6CF7-4929-BC673F4A2B79E2C5',
          Guid: 'B0CDBF90-32A4-4A59-884CB51C024E69D7',
          ContainerTitle: '2PM Update',
          Title: 'New Row 3 Jason Saunders',
          Type: 3,
          Priority: 0,
          Approved: false,
          OutputType: 0,
          Creator: 'J.SAUNDERS',
          ModBy: 'J.SAUNDERS',
          MosObjId: '',
          MosControl: false,
          ModTime: '2019-07-19T16:08:23Z',
          Expires: '2019-08-18T16:08:23Z',
          Owner: 'J.SAUNDERS',
          BeginText: null,
          FileStorageVersion: 0,
        },
        ObjectLinks: { LinkedRecords: { $id: '6', $values: [] } },
        SocialMediaLinks: [],
        ObjectTags: { Tags: [] },
        ChatData: [],
        IsSearchReturnedResult: false,
      },
      Float: false,
      Break: false,
      HasYellowTimingBar: false,
      CBreak: false,
      NotForBroadcast: false,
    },
    {
      CollectionsCollection: null,
      ScriptOrder: 7,
      PageNum: 'A7',
      FrontTime: '2023-12-28T19:00:46Z',
      FrontTimeFormatted: '07:00:46 PM',
      BackTime: '2023-12-28T19:05:00Z',
      BackTimeFormatted: '07:05:00 PM',
      FrontOverUnder: '-10675199.00:00:00',
      BackOverUnder: '-10675199.00:00:00',
      CumeTime: '00:00:46',
      CumeTimeFormatted: '0:46',
      BackCumeTime: '00:00:00',
      BackCumeTimeFormatted: '0:00',
      IsTimingBarSelected: false,
      IsRowFlashing: false,
      IsFrozen: false,
      RecordPointer: {
        ReadTime: 0,
        Actual: null,
        Estimated: '00:00:00',
        HardHitFront: '1800-01-01T00:00:00',
        HardHitBack: '1800-01-01T00:00:00',
        ActualTimeString: { Key: 'ReadTime', Value: '0:00' },
        DefaultLayout: null,
        Loading: false,
        ObjectProperties: [
          { FieldName: 'TextCommands', FieldValue: {} },
          { FieldName: 'Text', FieldValue: '' },
          { FieldName: 'VPContainsRTL', FieldValue: false },
          { FieldName: 'Owner', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'Creator', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'ModBy', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'AnchorTime', FieldValue: '2019-07-19T16:08:23Z' },
          { FieldName: 'Expires', FieldValue: '2019-08-18T16:08:23Z' },
          { FieldName: 'ModTime', FieldValue: '2019-07-19T16:08:23Z' },
          { FieldName: 'Type', FieldValue: 3 },
          { FieldName: 'SourceModBy', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'SourceModTime', FieldValue: '2019-07-19T16:07:19Z' },
          {
            FieldName: 'GUID',
            FieldValue: '0CF08823-DCE4-4A7E-AB294064724CAB45',
          },
          { FieldName: 'pubApproved', FieldValue: false },
          { FieldName: 'ScriptSubType', FieldValue: 'Broadcast' },
          { FieldName: 'Priority', FieldValue: 0 },
          { FieldName: 'Approved', FieldValue: false },
          { FieldName: 'Version', FieldValue: 0 },
          { FieldName: 'Status', FieldValue: '2' },
          { FieldName: 'WriteCount', FieldValue: 4 },
          { FieldName: 'RowModTime', FieldValue: '2023-12-28T12:00:01Z' },
          { FieldName: 'RowModBy', FieldValue: 'AutoCreate' },
          { FieldName: 'Database', FieldValue: 'svrscala-backup' },
          {
            FieldName: 'Path',
            FieldValue: 'P_NASNEWS\\W\\R_F9114187-6CF7-4929-BC673F4A2B79E2C5',
          },
          { FieldName: 'Title', FieldValue: 'New Row 5 Jason Saunders' },
          { FieldName: 'OutputType', FieldValue: 0 },
          { FieldName: 'PageNum', FieldValue: 'A7' },
          { FieldName: 'UserCanWritePermissions', FieldValue: true },
          { FieldName: 'CumeTime', FieldValue: 0 },
          { FieldName: 'DoNotArchive', FieldValue: false },
          { FieldName: 'MOSObjSlugs', FieldValue: '' },
          { FieldName: 'ObjectPlaceholderCreate', FieldValue: '' },
          { FieldName: 'MOSChannels', FieldValue: '' },
          { FieldName: 'Reporter', FieldValue: '' },
          { FieldName: 'MOSStatus', FieldValue: '' },
          { FieldName: 'Float', FieldValue: false },
          { FieldName: 'Break', FieldValue: false },
          { FieldName: 'Estimated', FieldValue: 0 },
          { FieldName: 'Actual', FieldValue: 0 },
          { FieldName: 'ReadTime', FieldValue: 0 },
          { FieldName: 'BackTime', FieldValue: '1800-01-01T00:00:00' },
        ],
        ListData: {
          ENPSDatabase: 'svrscala-backup',
          Path: 'P_NASNEWS\\W\\R_F9114187-6CF7-4929-BC673F4A2B79E2C5',
          Guid: '0CF08823-DCE4-4A7E-AB294064724CAB45',
          ContainerTitle: '2PM Update',
          Title: 'New Row 5 Jason Saunders',
          Type: 3,
          Priority: 0,
          Approved: false,
          OutputType: 0,
          Creator: 'J.SAUNDERS',
          ModBy: 'J.SAUNDERS',
          MosObjId: '',
          MosControl: false,
          ModTime: '2019-07-19T16:08:23Z',
          Expires: '2019-08-18T16:08:23Z',
          Owner: 'J.SAUNDERS',
          BeginText: null,
          FileStorageVersion: 0,
        },
        ObjectLinks: { LinkedRecords: { $id: '7', $values: [] } },
        SocialMediaLinks: [],
        ObjectTags: { Tags: [] },
        ChatData: [],
        IsSearchReturnedResult: false,
      },
      Float: false,
      Break: false,
      HasYellowTimingBar: false,
      CBreak: false,
      NotForBroadcast: false,
    },
    {
      CollectionsCollection: null,
      ScriptOrder: 8,
      PageNum: 'A8',
      FrontTime: '2023-12-28T19:00:46Z',
      FrontTimeFormatted: '07:00:46 PM',
      BackTime: '2023-12-28T19:05:00Z',
      BackTimeFormatted: '07:05:00 PM',
      FrontOverUnder: '-10675199.00:00:00',
      BackOverUnder: '-10675199.00:00:00',
      CumeTime: '00:00:46',
      CumeTimeFormatted: '0:46',
      BackCumeTime: '00:00:00',
      BackCumeTimeFormatted: '0:00',
      IsTimingBarSelected: false,
      IsRowFlashing: false,
      IsFrozen: false,
      RecordPointer: {
        ReadTime: 0,
        Actual: null,
        Estimated: '00:00:00',
        HardHitFront: '1800-01-01T00:00:00',
        HardHitBack: '1800-01-01T00:00:00',
        ActualTimeString: { Key: 'ReadTime', Value: '0:00' },
        DefaultLayout: null,
        Loading: false,
        ObjectProperties: [
          { FieldName: 'TextCommands', FieldValue: {} },
          { FieldName: 'Text', FieldValue: '' },
          { FieldName: 'VPContainsRTL', FieldValue: false },
          { FieldName: 'Owner', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'Creator', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'ModBy', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'AnchorTime', FieldValue: '2019-07-19T16:08:23Z' },
          { FieldName: 'Expires', FieldValue: '2019-08-18T16:08:23Z' },
          { FieldName: 'ModTime', FieldValue: '2019-07-19T16:08:23Z' },
          { FieldName: 'Type', FieldValue: 3 },
          { FieldName: 'SourceModBy', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'SourceModTime', FieldValue: '2019-07-19T16:07:24Z' },
          {
            FieldName: 'GUID',
            FieldValue: '6CAC8807-C2AD-445F-8E31462939D7EBB8',
          },
          { FieldName: 'pubApproved', FieldValue: false },
          { FieldName: 'ScriptSubType', FieldValue: 'Broadcast' },
          { FieldName: 'Priority', FieldValue: 0 },
          { FieldName: 'Approved', FieldValue: false },
          { FieldName: 'Version', FieldValue: 0 },
          { FieldName: 'Status', FieldValue: '2' },
          { FieldName: 'WriteCount', FieldValue: 4 },
          { FieldName: 'RowModTime', FieldValue: '2023-12-28T12:00:01Z' },
          { FieldName: 'RowModBy', FieldValue: 'AutoCreate' },
          { FieldName: 'Database', FieldValue: 'svrscala-backup' },
          {
            FieldName: 'Path',
            FieldValue: 'P_NASNEWS\\W\\R_F9114187-6CF7-4929-BC673F4A2B79E2C5',
          },
          { FieldName: 'Title', FieldValue: 'New Row 6 Jason Saunders' },
          { FieldName: 'OutputType', FieldValue: 0 },
          { FieldName: 'PageNum', FieldValue: 'A8' },
          { FieldName: 'UserCanWritePermissions', FieldValue: true },
          { FieldName: 'CumeTime', FieldValue: 0 },
          { FieldName: 'DoNotArchive', FieldValue: false },
          { FieldName: 'MOSObjSlugs', FieldValue: '' },
          { FieldName: 'ObjectPlaceholderCreate', FieldValue: '' },
          { FieldName: 'MOSChannels', FieldValue: '' },
          { FieldName: 'Reporter', FieldValue: '' },
          { FieldName: 'MOSStatus', FieldValue: '' },
          { FieldName: 'Float', FieldValue: false },
          { FieldName: 'Break', FieldValue: false },
          { FieldName: 'Estimated', FieldValue: 0 },
          { FieldName: 'Actual', FieldValue: 0 },
          { FieldName: 'ReadTime', FieldValue: 0 },
          { FieldName: 'BackTime', FieldValue: '1800-01-01T00:00:00' },
        ],
        ListData: {
          ENPSDatabase: 'svrscala-backup',
          Path: 'P_NASNEWS\\W\\R_F9114187-6CF7-4929-BC673F4A2B79E2C5',
          Guid: '6CAC8807-C2AD-445F-8E31462939D7EBB8',
          ContainerTitle: '2PM Update',
          Title: 'New Row 6 Jason Saunders',
          Type: 3,
          Priority: 0,
          Approved: false,
          OutputType: 0,
          Creator: 'J.SAUNDERS',
          ModBy: 'J.SAUNDERS',
          MosObjId: '',
          MosControl: false,
          ModTime: '2019-07-19T16:08:23Z',
          Expires: '2019-08-18T16:08:23Z',
          Owner: 'J.SAUNDERS',
          BeginText: null,
          FileStorageVersion: 0,
        },
        ObjectLinks: { LinkedRecords: { $id: '8', $values: [] } },
        SocialMediaLinks: [],
        ObjectTags: { Tags: [] },
        ChatData: [],
        IsSearchReturnedResult: false,
      },
      Float: false,
      Break: false,
      HasYellowTimingBar: false,
      CBreak: false,
      NotForBroadcast: false,
    },
    {
      CollectionsCollection: null,
      ScriptOrder: 9,
      PageNum: 'A9',
      FrontTime: '2023-12-28T19:00:46Z',
      FrontTimeFormatted: '07:00:46 PM',
      BackTime: '2023-12-28T19:05:00Z',
      BackTimeFormatted: '07:05:00 PM',
      FrontOverUnder: '-10675199.00:00:00',
      BackOverUnder: '-10675199.00:00:00',
      CumeTime: '00:00:46',
      CumeTimeFormatted: '0:46',
      BackCumeTime: '00:00:00',
      BackCumeTimeFormatted: '0:00',
      IsTimingBarSelected: false,
      IsRowFlashing: false,
      IsFrozen: false,
      RecordPointer: {
        ReadTime: 0,
        Actual: null,
        Estimated: '00:00:00',
        HardHitFront: '1800-01-01T00:00:00',
        HardHitBack: '1800-01-01T00:00:00',
        ActualTimeString: { Key: 'ReadTime', Value: '0:00' },
        DefaultLayout: null,
        Loading: false,
        ObjectProperties: [
          { FieldName: 'TextCommands', FieldValue: {} },
          { FieldName: 'Text', FieldValue: '' },
          { FieldName: 'VPContainsRTL', FieldValue: false },
          { FieldName: 'Owner', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'Creator', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'ModBy', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'AnchorTime', FieldValue: '2019-07-19T16:08:23Z' },
          { FieldName: 'Expires', FieldValue: '2019-08-18T16:08:23Z' },
          { FieldName: 'ModTime', FieldValue: '2019-07-19T16:08:23Z' },
          { FieldName: 'Type', FieldValue: 3 },
          { FieldName: 'SourceModBy', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'SourceModTime', FieldValue: '2019-07-19T16:07:30Z' },
          {
            FieldName: 'GUID',
            FieldValue: 'F6D7E348-CADC-4161-9173F3086F54CB5E',
          },
          { FieldName: 'pubApproved', FieldValue: false },
          { FieldName: 'ScriptSubType', FieldValue: 'Broadcast' },
          { FieldName: 'Priority', FieldValue: 0 },
          { FieldName: 'Approved', FieldValue: false },
          { FieldName: 'Version', FieldValue: 0 },
          { FieldName: 'Status', FieldValue: '2' },
          { FieldName: 'WriteCount', FieldValue: 4 },
          { FieldName: 'RowModTime', FieldValue: '2023-12-28T12:00:01Z' },
          { FieldName: 'RowModBy', FieldValue: 'AutoCreate' },
          { FieldName: 'Database', FieldValue: 'svrscala-backup' },
          {
            FieldName: 'Path',
            FieldValue: 'P_NASNEWS\\W\\R_F9114187-6CF7-4929-BC673F4A2B79E2C5',
          },
          { FieldName: 'Title', FieldValue: 'New Row 7 Jason Saunders' },
          { FieldName: 'OutputType', FieldValue: 0 },
          { FieldName: 'PageNum', FieldValue: 'A9' },
          { FieldName: 'UserCanWritePermissions', FieldValue: true },
          { FieldName: 'CumeTime', FieldValue: 0 },
          { FieldName: 'DoNotArchive', FieldValue: false },
          { FieldName: 'MOSObjSlugs', FieldValue: '' },
          { FieldName: 'ObjectPlaceholderCreate', FieldValue: '' },
          { FieldName: 'MOSChannels', FieldValue: '' },
          { FieldName: 'Reporter', FieldValue: '' },
          { FieldName: 'MOSStatus', FieldValue: '' },
          { FieldName: 'Float', FieldValue: false },
          { FieldName: 'Break', FieldValue: false },
          { FieldName: 'Estimated', FieldValue: 0 },
          { FieldName: 'Actual', FieldValue: 0 },
          { FieldName: 'ReadTime', FieldValue: 0 },
          { FieldName: 'BackTime', FieldValue: '1800-01-01T00:00:00' },
        ],
        ListData: {
          ENPSDatabase: 'svrscala-backup',
          Path: 'P_NASNEWS\\W\\R_F9114187-6CF7-4929-BC673F4A2B79E2C5',
          Guid: 'F6D7E348-CADC-4161-9173F3086F54CB5E',
          ContainerTitle: '2PM Update',
          Title: 'New Row 7 Jason Saunders',
          Type: 3,
          Priority: 0,
          Approved: false,
          OutputType: 0,
          Creator: 'J.SAUNDERS',
          ModBy: 'J.SAUNDERS',
          MosObjId: '',
          MosControl: false,
          ModTime: '2019-07-19T16:08:23Z',
          Expires: '2019-08-18T16:08:23Z',
          Owner: 'J.SAUNDERS',
          BeginText: null,
          FileStorageVersion: 0,
        },
        ObjectLinks: { LinkedRecords: { $id: '9', $values: [] } },
        SocialMediaLinks: [],
        ObjectTags: { Tags: [] },
        ChatData: [],
        IsSearchReturnedResult: false,
      },
      Float: false,
      Break: false,
      HasYellowTimingBar: false,
      CBreak: false,
      NotForBroadcast: false,
    },
    {
      CollectionsCollection: null,
      ScriptOrder: 10,
      PageNum: 'A10',
      FrontTime: '2023-12-28T19:00:46Z',
      FrontTimeFormatted: '07:00:46 PM',
      BackTime: '2023-12-28T19:05:00Z',
      BackTimeFormatted: '07:05:00 PM',
      FrontOverUnder: '-10675199.00:00:00',
      BackOverUnder: '-10675199.00:00:00',
      CumeTime: '00:00:46',
      CumeTimeFormatted: '0:46',
      BackCumeTime: '00:00:00',
      BackCumeTimeFormatted: '0:00',
      IsTimingBarSelected: false,
      IsRowFlashing: false,
      IsFrozen: false,
      RecordPointer: {
        ReadTime: 0,
        Actual: null,
        Estimated: '00:00:00',
        HardHitFront: '1800-01-01T00:00:00',
        HardHitBack: '1800-01-01T00:00:00',
        ActualTimeString: { Key: 'ReadTime', Value: '0:00' },
        DefaultLayout: null,
        Loading: false,
        ObjectProperties: [
          { FieldName: 'TextCommands', FieldValue: {} },
          { FieldName: 'Text', FieldValue: '' },
          { FieldName: 'VPContainsRTL', FieldValue: false },
          { FieldName: 'Owner', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'Creator', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'ModBy', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'AnchorTime', FieldValue: '2019-07-19T16:08:23Z' },
          { FieldName: 'Expires', FieldValue: '2019-08-18T16:08:23Z' },
          { FieldName: 'ModTime', FieldValue: '2019-07-19T16:08:23Z' },
          { FieldName: 'Type', FieldValue: 3 },
          { FieldName: 'SourceModBy', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'SourceModTime', FieldValue: '2019-07-19T16:07:54Z' },
          {
            FieldName: 'GUID',
            FieldValue: '8AB07E39-DFDD-476B-AA88C4BD8B0E7883',
          },
          { FieldName: 'pubApproved', FieldValue: false },
          { FieldName: 'ScriptSubType', FieldValue: 'Broadcast' },
          { FieldName: 'Priority', FieldValue: 0 },
          { FieldName: 'Approved', FieldValue: false },
          { FieldName: 'Version', FieldValue: 0 },
          { FieldName: 'Status', FieldValue: '2' },
          { FieldName: 'WriteCount', FieldValue: 4 },
          { FieldName: 'RowModTime', FieldValue: '2023-12-28T12:00:01Z' },
          { FieldName: 'RowModBy', FieldValue: 'AutoCreate' },
          { FieldName: 'Database', FieldValue: 'svrscala-backup' },
          {
            FieldName: 'Path',
            FieldValue: 'P_NASNEWS\\W\\R_F9114187-6CF7-4929-BC673F4A2B79E2C5',
          },
          { FieldName: 'Title', FieldValue: 'New Row 9 Jason Saunders' },
          { FieldName: 'OutputType', FieldValue: 0 },
          { FieldName: 'PageNum', FieldValue: 'A10' },
          { FieldName: 'UserCanWritePermissions', FieldValue: true },
          { FieldName: 'CumeTime', FieldValue: 0 },
          { FieldName: 'DoNotArchive', FieldValue: false },
          { FieldName: 'MOSObjSlugs', FieldValue: '' },
          { FieldName: 'ObjectPlaceholderCreate', FieldValue: '' },
          { FieldName: 'MOSChannels', FieldValue: '' },
          { FieldName: 'Reporter', FieldValue: '' },
          { FieldName: 'MOSStatus', FieldValue: '' },
          { FieldName: 'Float', FieldValue: false },
          { FieldName: 'Break', FieldValue: false },
          { FieldName: 'Estimated', FieldValue: 0 },
          { FieldName: 'Actual', FieldValue: 0 },
          { FieldName: 'ReadTime', FieldValue: 0 },
          { FieldName: 'BackTime', FieldValue: '1800-01-01T00:00:00' },
        ],
        ListData: {
          ENPSDatabase: 'svrscala-backup',
          Path: 'P_NASNEWS\\W\\R_F9114187-6CF7-4929-BC673F4A2B79E2C5',
          Guid: '8AB07E39-DFDD-476B-AA88C4BD8B0E7883',
          ContainerTitle: '2PM Update',
          Title: 'New Row 9 Jason Saunders',
          Type: 3,
          Priority: 0,
          Approved: false,
          OutputType: 0,
          Creator: 'J.SAUNDERS',
          ModBy: 'J.SAUNDERS',
          MosObjId: '',
          MosControl: false,
          ModTime: '2019-07-19T16:08:23Z',
          Expires: '2019-08-18T16:08:23Z',
          Owner: 'J.SAUNDERS',
          BeginText: null,
          FileStorageVersion: 0,
        },
        ObjectLinks: { LinkedRecords: { $id: '10', $values: [] } },
        SocialMediaLinks: [],
        ObjectTags: { Tags: [] },
        ChatData: [],
        IsSearchReturnedResult: false,
      },
      Float: false,
      Break: false,
      HasYellowTimingBar: false,
      CBreak: false,
      NotForBroadcast: false,
    },
    {
      CollectionsCollection: null,
      ScriptOrder: 11,
      PageNum: 'A11',
      FrontTime: '2023-12-28T19:00:46Z',
      FrontTimeFormatted: '07:00:46 PM',
      BackTime: '2023-12-28T19:05:00Z',
      BackTimeFormatted: '07:05:00 PM',
      FrontOverUnder: '-10675199.00:00:00',
      BackOverUnder: '-10675199.00:00:00',
      CumeTime: '00:00:46',
      CumeTimeFormatted: '0:46',
      BackCumeTime: '00:00:00',
      BackCumeTimeFormatted: '0:00',
      IsTimingBarSelected: false,
      IsRowFlashing: false,
      IsFrozen: false,
      RecordPointer: {
        ReadTime: 0,
        Actual: null,
        Estimated: '00:00:00',
        HardHitFront: '1800-01-01T00:00:00',
        HardHitBack: '1800-01-01T00:00:00',
        ActualTimeString: { Key: 'ReadTime', Value: '0:00' },
        DefaultLayout: null,
        Loading: false,
        ObjectProperties: [
          { FieldName: 'TextCommands', FieldValue: {} },
          { FieldName: 'Text', FieldValue: '' },
          { FieldName: 'VPContainsRTL', FieldValue: false },
          { FieldName: 'Owner', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'Creator', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'ModBy', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'AnchorTime', FieldValue: '2019-07-19T16:08:23Z' },
          { FieldName: 'Expires', FieldValue: '2019-08-18T16:08:23Z' },
          { FieldName: 'ModTime', FieldValue: '2019-07-19T16:08:23Z' },
          { FieldName: 'Type', FieldValue: 3 },
          { FieldName: 'SourceModBy', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'SourceModTime', FieldValue: '2019-07-19T16:07:44Z' },
          {
            FieldName: 'GUID',
            FieldValue: '63DD68C7-C8E7-4A46-B8AC31FCD3615E07',
          },
          { FieldName: 'pubApproved', FieldValue: false },
          { FieldName: 'ScriptSubType', FieldValue: 'Broadcast' },
          { FieldName: 'Priority', FieldValue: 0 },
          { FieldName: 'Approved', FieldValue: false },
          { FieldName: 'Version', FieldValue: 0 },
          { FieldName: 'Status', FieldValue: '2' },
          { FieldName: 'WriteCount', FieldValue: 4 },
          { FieldName: 'RowModTime', FieldValue: '2023-12-28T12:00:01Z' },
          { FieldName: 'RowModBy', FieldValue: 'AutoCreate' },
          { FieldName: 'Database', FieldValue: 'svrscala-backup' },
          {
            FieldName: 'Path',
            FieldValue: 'P_NASNEWS\\W\\R_F9114187-6CF7-4929-BC673F4A2B79E2C5',
          },
          { FieldName: 'Title', FieldValue: 'New Row 8 Jason Saunders' },
          { FieldName: 'OutputType', FieldValue: 0 },
          { FieldName: 'PageNum', FieldValue: 'A11' },
          { FieldName: 'UserCanWritePermissions', FieldValue: true },
          { FieldName: 'CumeTime', FieldValue: 0 },
          { FieldName: 'DoNotArchive', FieldValue: false },
          { FieldName: 'MOSObjSlugs', FieldValue: '' },
          { FieldName: 'ObjectPlaceholderCreate', FieldValue: '' },
          { FieldName: 'MOSChannels', FieldValue: '' },
          { FieldName: 'Reporter', FieldValue: '' },
          { FieldName: 'MOSStatus', FieldValue: '' },
          { FieldName: 'Float', FieldValue: false },
          { FieldName: 'Break', FieldValue: false },
          { FieldName: 'Estimated', FieldValue: 0 },
          { FieldName: 'Actual', FieldValue: 0 },
          { FieldName: 'ReadTime', FieldValue: 0 },
          { FieldName: 'BackTime', FieldValue: '1800-01-01T00:00:00' },
        ],
        ListData: {
          ENPSDatabase: 'svrscala-backup',
          Path: 'P_NASNEWS\\W\\R_F9114187-6CF7-4929-BC673F4A2B79E2C5',
          Guid: '63DD68C7-C8E7-4A46-B8AC31FCD3615E07',
          ContainerTitle: '2PM Update',
          Title: 'New Row 8 Jason Saunders',
          Type: 3,
          Priority: 0,
          Approved: false,
          OutputType: 0,
          Creator: 'J.SAUNDERS',
          ModBy: 'J.SAUNDERS',
          MosObjId: '',
          MosControl: false,
          ModTime: '2019-07-19T16:08:23Z',
          Expires: '2019-08-18T16:08:23Z',
          Owner: 'J.SAUNDERS',
          BeginText: null,
          FileStorageVersion: 0,
        },
        ObjectLinks: { LinkedRecords: { $id: '11', $values: [] } },
        SocialMediaLinks: [],
        ObjectTags: { Tags: [] },
        ChatData: [],
        IsSearchReturnedResult: false,
      },
      Float: false,
      Break: false,
      HasYellowTimingBar: false,
      CBreak: false,
      NotForBroadcast: false,
    },
    {
      CollectionsCollection: null,
      ScriptOrder: 12,
      PageNum: 'A12',
      FrontTime: '2023-12-28T19:00:46Z',
      FrontTimeFormatted: '07:00:46 PM',
      BackTime: '2023-12-28T19:05:00Z',
      BackTimeFormatted: '07:05:00 PM',
      FrontOverUnder: '-10675199.00:00:00',
      BackOverUnder: '-10675199.00:00:00',
      CumeTime: '00:00:46',
      CumeTimeFormatted: '0:46',
      BackCumeTime: '00:00:00',
      BackCumeTimeFormatted: '0:00',
      IsTimingBarSelected: false,
      IsRowFlashing: false,
      IsFrozen: false,
      RecordPointer: {
        ReadTime: 0,
        Actual: null,
        Estimated: '00:00:00',
        HardHitFront: '1800-01-01T00:00:00',
        HardHitBack: '1800-01-01T00:00:00',
        ActualTimeString: { Key: 'ReadTime', Value: '0:00' },
        DefaultLayout: null,
        Loading: false,
        ObjectProperties: [
          { FieldName: 'TextCommands', FieldValue: {} },
          { FieldName: 'Text', FieldValue: '' },
          { FieldName: 'VPContainsRTL', FieldValue: false },
          { FieldName: 'Owner', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'Creator', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'ModBy', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'AnchorTime', FieldValue: '2019-07-19T16:08:23Z' },
          { FieldName: 'Expires', FieldValue: '2019-08-18T16:08:23Z' },
          { FieldName: 'ModTime', FieldValue: '2019-07-19T16:08:23Z' },
          { FieldName: 'Type', FieldValue: 3 },
          { FieldName: 'SourceModBy', FieldValue: 'J.SAUNDERS' },
          { FieldName: 'SourceModTime', FieldValue: '2019-07-19T16:07:57Z' },
          {
            FieldName: 'GUID',
            FieldValue: '287CCF19-AB47-4D8E-9C81359AE1165B2B',
          },
          { FieldName: 'pubApproved', FieldValue: false },
          { FieldName: 'ScriptSubType', FieldValue: 'Broadcast' },
          { FieldName: 'Priority', FieldValue: 0 },
          { FieldName: 'Approved', FieldValue: false },
          { FieldName: 'Version', FieldValue: 0 },
          { FieldName: 'Status', FieldValue: '2' },
          { FieldName: 'WriteCount', FieldValue: 4 },
          { FieldName: 'RowModTime', FieldValue: '2023-12-28T12:00:01Z' },
          { FieldName: 'RowModBy', FieldValue: 'AutoCreate' },
          { FieldName: 'Database', FieldValue: 'svrscala-backup' },
          {
            FieldName: 'Path',
            FieldValue: 'P_NASNEWS\\W\\R_F9114187-6CF7-4929-BC673F4A2B79E2C5',
          },
          { FieldName: 'Title', FieldValue: 'New Row 10 Jason Saunders' },
          { FieldName: 'OutputType', FieldValue: 0 },
          { FieldName: 'PageNum', FieldValue: 'A12' },
          { FieldName: 'UserCanWritePermissions', FieldValue: true },
          { FieldName: 'CumeTime', FieldValue: 0 },
          { FieldName: 'DoNotArchive', FieldValue: false },
          { FieldName: 'MOSObjSlugs', FieldValue: '' },
          { FieldName: 'ObjectPlaceholderCreate', FieldValue: '' },
          { FieldName: 'MOSChannels', FieldValue: '' },
          { FieldName: 'Reporter', FieldValue: '' },
          { FieldName: 'MOSStatus', FieldValue: '' },
          { FieldName: 'Float', FieldValue: false },
          { FieldName: 'Break', FieldValue: false },
          { FieldName: 'Estimated', FieldValue: 0 },
          { FieldName: 'Actual', FieldValue: 0 },
          { FieldName: 'ReadTime', FieldValue: 0 },
          { FieldName: 'BackTime', FieldValue: '1800-01-01T00:00:00' },
        ],
        ListData: {
          ENPSDatabase: 'svrscala-backup',
          Path: 'P_NASNEWS\\W\\R_F9114187-6CF7-4929-BC673F4A2B79E2C5',
          Guid: '287CCF19-AB47-4D8E-9C81359AE1165B2B',
          ContainerTitle: '2PM Update',
          Title: 'New Row 10 Jason Saunders',
          Type: 3,
          Priority: 0,
          Approved: false,
          OutputType: 0,
          Creator: 'J.SAUNDERS',
          ModBy: 'J.SAUNDERS',
          MosObjId: '',
          MosControl: false,
          ModTime: '2019-07-19T16:08:23Z',
          Expires: '2019-08-18T16:08:23Z',
          Owner: 'J.SAUNDERS',
          BeginText: null,
          FileStorageVersion: 0,
        },
        ObjectLinks: { LinkedRecords: { $id: '12', $values: [] } },
        SocialMediaLinks: [],
        ObjectTags: { Tags: [] },
        ChatData: [],
        IsSearchReturnedResult: false,
      },
      Float: false,
      Break: false,
      HasYellowTimingBar: false,
      CBreak: false,
      NotForBroadcast: false,
    },
    {
      CollectionsCollection: null,
      ScriptOrder: 13,
      PageNum: null,
      FrontTime: '0001-01-01T00:00:00',
      FrontTimeFormatted: '12:00:00 AM',
      BackTime: '0001-01-01T00:00:00',
      BackTimeFormatted: '12:00:00 AM',
      FrontOverUnder: '00:00:00',
      BackOverUnder: '00:00:00',
      CumeTime: '00:00:00',
      CumeTimeFormatted: '0:00',
      BackCumeTime: '00:00:00',
      BackCumeTimeFormatted: '0:00',
      IsTimingBarSelected: false,
      IsRowFlashing: false,
      IsFrozen: false,
      RecordPointer: {
        ReadTime: 0,
        Actual: null,
        Estimated: '00:00:00',
        HardHitFront: '1800-01-01T00:00:00',
        HardHitBack: '1800-01-01T00:00:00',
        ActualTimeString: { Key: 'ReadTime', Value: '0:00' },
        DefaultLayout: null,
        Loading: false,
        ObjectProperties: [
          { FieldName: 'Guid', FieldValue: '0' },
          { FieldName: 'UserCanWritePermissions', FieldValue: true },
          { FieldName: 'CumeTime', FieldValue: 0 },
          { FieldName: 'DoNotArchive', FieldValue: false },
          { FieldName: 'MOSObjSlugs', FieldValue: '' },
          { FieldName: 'ObjectPlaceholderCreate', FieldValue: '' },
          { FieldName: 'MOSChannels', FieldValue: '' },
          { FieldName: 'Reporter', FieldValue: '' },
          { FieldName: 'MOSStatus', FieldValue: '' },
          { FieldName: 'Float', FieldValue: false },
          { FieldName: 'ModBy', FieldValue: '' },
          { FieldName: 'Break', FieldValue: false },
          { FieldName: 'Approved', FieldValue: false },
          { FieldName: 'Estimated', FieldValue: 0 },
          { FieldName: 'Actual', FieldValue: 0 },
          { FieldName: 'ReadTime', FieldValue: 0 },
          { FieldName: 'BackTime', FieldValue: '1800-01-01T00:00:00' },
        ],
        ListData: {
          ENPSDatabase: '',
          Path: '',
          Guid: '0',
          ContainerTitle: null,
          Title: '',
          Type: 0,
          Priority: 0,
          Approved: false,
          OutputType: 0,
          Creator: null,
          ModBy: null,
          MosObjId: '',
          MosControl: false,
          ModTime: '0001-01-01T00:00:00',
          Expires: '0001-01-01T00:00:00',
          Owner: null,
          BeginText: null,
          FileStorageVersion: 0,
        },
        ObjectLinks: { LinkedRecords: { $id: '13', $values: [] } },
        SocialMediaLinks: [],
        ObjectTags: { Tags: [] },
        ChatData: [],
        IsSearchReturnedResult: false,
      },
      Float: false,
      Break: false,
      HasYellowTimingBar: false,
      CBreak: false,
      NotForBroadcast: false,
    },
  ],
  UpdatesSuspended: false,
  SuspendRowFlashing: false,
  HasPendingChanges: false,
  OnAir: false,
  LTTRecording: false,
  TimeFormat: 0,
  DefaultLayout: {
    DefaultLayout: [
      {
        ColumnName: 'PageNum',
        ColumnWidth: 600,
        ColumnDisplayName: 'Page',
        ColumnWordWrap: false,
        ColumnAutoSizeWidth: false,
        ColumnJustification: 'Left',
        ColumnValidation: 'Text',
        ColumnList: '',
        IsReadOnly: false,
        SortOrder: 0,
        ColumnMaxLen: '5',
        ColumnExtractTarget: false,
      },
      {
        ColumnName: 'RowStatus',
        ColumnWidth: 150,
        ColumnDisplayName: '',
        ColumnWordWrap: false,
        ColumnAutoSizeWidth: false,
        ColumnJustification: 'Left',
        ColumnValidation: 'Text',
        ColumnList: '',
        IsReadOnly: true,
        SortOrder: 1,
        ColumnMaxLen: '',
        ColumnExtractTarget: false,
      },
      {
        ColumnName: 'Slug',
        ColumnWidth: 2790,
        ColumnDisplayName: 'Story Slug',
        ColumnWordWrap: false,
        ColumnAutoSizeWidth: false,
        ColumnJustification: 'Left',
        ColumnValidation: 'Text',
        ColumnList: '',
        IsReadOnly: false,
        SortOrder: 2,
        ColumnMaxLen: '',
        ColumnExtractTarget: false,
      },
      {
        ColumnName: 'SegStatus',
        ColumnWidth: 210,
        ColumnDisplayName: '',
        ColumnWordWrap: false,
        ColumnAutoSizeWidth: false,
        ColumnJustification: 'Left',
        ColumnValidation: 'Text',
        ColumnList: '',
        IsReadOnly: true,
        SortOrder: 3,
        ColumnMaxLen: '',
        ColumnExtractTarget: false,
      },
      {
        ColumnName: 'Segment',
        ColumnWidth: 915,
        ColumnDisplayName: 'Segment',
        ColumnWordWrap: false,
        ColumnAutoSizeWidth: false,
        ColumnJustification: 'Left',
        ColumnValidation: 'Text',
        ColumnList: '',
        IsReadOnly: false,
        SortOrder: 4,
        ColumnMaxLen: '',
        ColumnExtractTarget: false,
      },
      {
        ColumnName: 'CumeTime',
        ColumnWidth: 1005,
        ColumnDisplayName: 'Cume',
        ColumnWordWrap: false,
        ColumnAutoSizeWidth: false,
        ColumnJustification: 'Right',
        ColumnValidation: 'Duration',
        ColumnList: '',
        IsReadOnly: true,
        SortOrder: 5,
        ColumnMaxLen: '',
        ColumnExtractTarget: false,
      },
      {
        ColumnName: 'DoNotArchive',
        ColumnWidth: 1000,
        ColumnDisplayName: 'DoNotArchive',
        ColumnWordWrap: false,
        ColumnAutoSizeWidth: false,
        ColumnJustification: 'Left',
        ColumnValidation: 'CheckBox',
        ColumnList: '',
        IsReadOnly: false,
        SortOrder: 6,
        ColumnMaxLen: '0',
        ColumnExtractTarget: false,
      },
      {
        ColumnName: 'MOSObjSlugs',
        ColumnWidth: 3855,
        ColumnDisplayName: 'MOS Obj Slug',
        ColumnWordWrap: true,
        ColumnAutoSizeWidth: true,
        ColumnJustification: 'Left',
        ColumnValidation: 'Text',
        ColumnList: '',
        IsReadOnly: true,
        SortOrder: 7,
        ColumnMaxLen: '',
        ColumnExtractTarget: false,
      },
      {
        ColumnName: 'ObjectPlaceholderCreate',
        ColumnWidth: 1005,
        ColumnDisplayName: 'Object Placeholder Create',
        ColumnWordWrap: false,
        ColumnAutoSizeWidth: false,
        ColumnJustification: 'Left',
        ColumnValidation: 'Table',
        ColumnList: 'group1|group2|group3',
        IsReadOnly: false,
        SortOrder: 8,
        ColumnMaxLen: '',
        ColumnExtractTarget: false,
      },
      {
        ColumnName: 'MOSChannels',
        ColumnWidth: 1275,
        ColumnDisplayName: 'MOS Channels',
        ColumnWordWrap: true,
        ColumnAutoSizeWidth: false,
        ColumnJustification: 'Left',
        ColumnValidation: 'MOSAutomation',
        ColumnList: '',
        IsReadOnly: false,
        SortOrder: 9,
        ColumnMaxLen: '',
        ColumnExtractTarget: false,
      },
      {
        ColumnName: 'Reporter',
        ColumnWidth: 1005,
        ColumnDisplayName: 'Reporter',
        ColumnWordWrap: false,
        ColumnAutoSizeWidth: false,
        ColumnJustification: 'Left',
        ColumnValidation: 'Text',
        ColumnList: '',
        IsReadOnly: false,
        SortOrder: 10,
        ColumnMaxLen: '0',
        ColumnExtractTarget: false,
      },
      {
        ColumnName: 'MOSStatus',
        ColumnWidth: 1575,
        ColumnDisplayName: 'MOS Status',
        ColumnWordWrap: true,
        ColumnAutoSizeWidth: true,
        ColumnJustification: 'Left',
        ColumnValidation: 'Text',
        ColumnList: '',
        IsReadOnly: true,
        SortOrder: 11,
        ColumnMaxLen: '',
        ColumnExtractTarget: false,
      },
      {
        ColumnName: 'Float',
        ColumnWidth: 600,
        ColumnDisplayName: 'Float',
        ColumnWordWrap: false,
        ColumnAutoSizeWidth: false,
        ColumnJustification: 'Center',
        ColumnValidation: 'CheckBox',
        ColumnList: '',
        IsReadOnly: false,
        SortOrder: 12,
        ColumnMaxLen: '',
        ColumnExtractTarget: false,
      },
      {
        ColumnName: 'ModBy',
        ColumnWidth: 1200,
        ColumnDisplayName: 'Last Mod By',
        ColumnWordWrap: false,
        ColumnAutoSizeWidth: false,
        ColumnJustification: 'Left',
        ColumnValidation: 'Text',
        ColumnList: '',
        IsReadOnly: true,
        SortOrder: 13,
        ColumnMaxLen: '',
        ColumnExtractTarget: false,
      },
      {
        ColumnName: 'Break',
        ColumnWidth: 600,
        ColumnDisplayName: 'Break',
        ColumnWordWrap: false,
        ColumnAutoSizeWidth: false,
        ColumnJustification: 'Center',
        ColumnValidation: 'CheckBox',
        ColumnList: '',
        IsReadOnly: false,
        SortOrder: 14,
        ColumnMaxLen: '',
        ColumnExtractTarget: false,
      },
      {
        ColumnName: 'Approved',
        ColumnWidth: 600,
        ColumnDisplayName: 'Final Appr',
        ColumnWordWrap: false,
        ColumnAutoSizeWidth: false,
        ColumnJustification: 'Center',
        ColumnValidation: 'CheckBox',
        ColumnList: '',
        IsReadOnly: false,
        SortOrder: 15,
        ColumnMaxLen: '',
        ColumnExtractTarget: false,
      },
      {
        ColumnName: 'Estimated',
        ColumnWidth: 840,
        ColumnDisplayName: 'Est Duration',
        ColumnWordWrap: false,
        ColumnAutoSizeWidth: false,
        ColumnJustification: 'Right',
        ColumnValidation: 'Duration',
        ColumnList: '',
        IsReadOnly: false,
        SortOrder: 16,
        ColumnMaxLen: '',
        ColumnExtractTarget: false,
      },
      {
        ColumnName: 'Actual',
        ColumnWidth: 720,
        ColumnDisplayName: 'Actual',
        ColumnWordWrap: false,
        ColumnAutoSizeWidth: false,
        ColumnJustification: 'Right',
        ColumnValidation: 'Duration',
        ColumnList: '',
        IsReadOnly: false,
        SortOrder: 17,
        ColumnMaxLen: '',
        ColumnExtractTarget: false,
      },
      {
        ColumnName: 'BackTime',
        ColumnWidth: 1005,
        ColumnDisplayName: 'Back',
        ColumnWordWrap: false,
        ColumnAutoSizeWidth: false,
        ColumnJustification: 'Right',
        ColumnValidation: 'Time',
        ColumnList: '',
        IsReadOnly: true,
        SortOrder: 18,
        ColumnMaxLen: '',
        ColumnExtractTarget: false,
      },
    ],
    DefaultLayoutType: 5,
  },
  Loading: false,
  ObjectProperties: [
    {
      FieldName: 'Sequence',
      FieldValue: [
        '6141794A-A342-4D6A-A26C90A0639CA9F7',
        'FBCD6414-5CB9-4264-97DB5569454D03C6',
        '913436FE-100E-4883-AAE9244055AE3876',
        '12375D2D-08AB-42E6-A2466AB07E0E7398',
        'A240D06D-7D06-44BC-8A75210AB40155C6',
        'B0CDBF90-32A4-4A59-884CB51C024E69D7',
        '0CF08823-DCE4-4A7E-AB294064724CAB45',
        '6CAC8807-C2AD-445F-8E31462939D7EBB8',
        'F6D7E348-CADC-4161-9173F3086F54CB5E',
        '8AB07E39-DFDD-476B-AA88C4BD8B0E7883',
        '63DD68C7-C8E7-4A46-B8AC31FCD3615E07',
        '287CCF19-AB47-4D8E-9C81359AE1165B2B',
        '0',
      ],
    },
    { FieldName: 'Type', FieldValue: 2 },
    { FieldName: 'pubApproved', FieldValue: false },
    { FieldName: 'AnchorTime', FieldValue: '2023-12-28T19:00:00Z' },
    { FieldName: 'LocalStartTime', FieldValue: '2023-12-28T14:00:00-05:00' },
    { FieldName: 'StartTime', FieldValue: '2023-12-28T19:00:00Z' },
    { FieldName: 'Expires', FieldValue: '2024-01-27T19:00:00Z' },
    { FieldName: 'ModTime', FieldValue: '2023-12-28T19:00:00Z' },
    { FieldName: 'EndTime', FieldValue: '2023-12-28T19:05:00Z' },
    { FieldName: 'FixedDuration', FieldValue: true },
    { FieldName: 'RundownDuration', FieldValue: '5:00' },
    { FieldName: 'SortScriptTemplates', FieldValue: '0' },
    { FieldName: 'MOSroEdStart', FieldValue: '2023-12-28T19:00:00Z' },
    { FieldName: 'MOSroEdDur', FieldValue: '00:05:00' },
    { FieldName: 'GUID', FieldValue: 'F9114187-6CF7-4929-BC673F4A2B79E2C5' },
    { FieldName: 'AutoCreateDays', FieldValue: '1;2;3;4;5' },
    { FieldName: 'AutoCreateTime', FieldValue: '1899-12-30T12:00:00Z' },
    { FieldName: 'AutoArchive', FieldValue: true },
    { FieldName: 'Creator', FieldValue: 'AutoCreate' },
    { FieldName: 'Owner', FieldValue: 'AutoCreate' },
    { FieldName: 'ModBy', FieldValue: 'AutoCreate' },
    { FieldName: 'ROSubType', FieldValue: 'Broadcast' },
    { FieldName: 'Priority', FieldValue: 0 },
    { FieldName: 'Version', FieldValue: 0 },
    { FieldName: 'Status', FieldValue: '2' },
    { FieldName: 'WriteCount', FieldValue: 1442 },
    { FieldName: 'RowModTime', FieldValue: '2023-12-28T18:12:28Z' },
    {
      FieldName: 'Layout',
      FieldValue:
        'PageNum\t600\r\nRowStatus\t150\r\nSlug\t2790\r\nSegStatus\t210\r\nSegment\t915\r\nCumeTime\t1005\r\nDoNotArchive\t1000\r\nMOSObjSlugs\t3855\r\nObjectPlaceholderCreate\t1005\r\nMOSChannels\t1275\r\nReporter\t1005\r\nMOSStatus\t1575\r\nFloat\t600\r\nModBy\t1200\r\nBreak\t600\r\nApproved\t600\r\nEstimated\t840\r\nActual\t720\r\nBackTime\t1005',
    },
    { FieldName: 'AutoCreateDate', FieldValue: '20231228120005' },
    { FieldName: 'MOSControl', FieldValue: true },
    {
      FieldName: 'LastCreatedRO',
      FieldValue:
        'SVRSCALA-BACKUP;P_NASNEWS\\W;78D04895-F0DC-425B-BE80ABE59A7CCB00',
    },
    { FieldName: 'RowModBy', FieldValue: 'L.DAVIS' },
    {
      FieldName: 'MOSIDTable',
      FieldValue:
        '6141794A-A342-4D6A-A26C90A0639CA9F7=zns.precis1.nassau.mos\u0010A240D06D-7D06-44BC-8A75210AB40155C6=zns.precis1.nassau.mos',
    },
    {
      FieldName: 'MOSStorySendTargets',
      FieldValue: [
        {
          MOSID: 'harris.mplm.mos',
          StartTime: '1800-01-01T00:00:00',
          IsChecked: true,
        },
        {
          MOSID: 'PROMPTER',
          StartTime: '1800-01-01T00:00:00',
          IsChecked: true,
        },
        {
          MOSID: 'zns.precis1.nassau.mos',
          StartTime: '1800-01-01T00:00:00',
          IsChecked: true,
        },
        { MOSID: '', StartTime: '1800-01-01T00:00:00Z', IsChecked: false },
      ],
    },
    { FieldName: 'Database', FieldValue: 'svrscala-backup' },
    { FieldName: 'Path', FieldValue: 'P_NASNEWS\\W' },
    { FieldName: 'Title', FieldValue: '2PM Update' },
    { FieldName: 'OutputType', FieldValue: 0 },
    { FieldName: 'HitTime', FieldValue: '1800-01-01T00:00:00' },
    { FieldName: 'CurrentID', FieldValue: '' },
    { FieldName: 'OnAir', FieldValue: false },
    { FieldName: 'LTTRecording', FieldValue: false },
    { FieldName: 'LTTPaused', FieldValue: false },
    { FieldName: 'UserCanWritePermissions', FieldValue: true },
    { FieldName: 'UserRDScriptPermissions', FieldValue: 3 },
  ],
  ListData: {
    ENPSDatabase: 'svrscala-backup',
    Path: 'P_NASNEWS\\W',
    Guid: 'F9114187-6CF7-4929-BC673F4A2B79E2C5',
    ContainerTitle: null,
    Title: '2PM Update',
    Type: 2,
    Priority: 0,
    Approved: false,
    OutputType: 0,
    Creator: 'AutoCreate',
    ModBy: 'AutoCreate',
    MosObjId: '',
    MosControl: true,
    ModTime: '2023-12-28T19:00:00Z',
    Expires: '2024-01-27T19:00:00Z',
    Owner: 'AutoCreate',
    BeginText: null,
    FileStorageVersion: 0,
  },
  ObjectLinks: { LinkedRecords: { $id: '14', $values: [] } },
  SocialMediaLinks: [],
  ObjectTags: { Tags: [] },
  ChatData: [],
  IsSearchReturnedResult: false,
}
